// packages/react/src/fields/temporal-fields.tsx
import { useField } from '../use-field.js'
import { FieldShell } from './internals.js'
import type { FieldComponentProps } from './internals.js'


/**
 * The temporal controls, each holding one canonical fixed-width string.
 *
 * One file per control, because a control changes for its own reasons.
 * These were one 2,154-line file — the largest in the repository.
 */
export function DateField({ path, label }: FieldComponentProps) {
  const field = useField(path)
  return (
    <FieldShell path={path} field={field} label={label}>
      <input
        type="date"
        {...field.controlProps}
        value={typeof field.value === 'string' ? field.value : ''}
        onChange={(event) => field.setValue(event.target.value === '' ? null : event.target.value)}
        onBlur={() => field.touch()}
      />
    </FieldShell>
  )
}

/**
 * A time of day, as `HH:MM`.
 *
 * `<input type="time">` gives the platform's own picker, its own keyboard handling
 * and its own locale display — a 12-hour clock where the reader expects one — while
 * its `value` is always `HH:MM` on a 24-hour clock. That is exactly the split the
 * format wants: the reader sees their convention, the answer records one canonical
 * shape.
 *
 * `step` is not set, so the browser offers no seconds. A time answer has none, and a
 * control offering a precision the format discards is a control that loses what
 * somebody typed.
 */
export function TimeField({ path, label }: FieldComponentProps) {
  const field = useField(path)
  return (
    <FieldShell path={path} field={field} label={label}>
      <input
        type="time"
        {...field.controlProps}
        /* Bounds are handed to the browser as well as checked by the engine. The
           engine's check is the truth — it runs again on the server — and this is
           what lets the platform grey out what it will not accept, which is a better
           experience than a message after the fact. */
        {...(typeof field.def.earliest === 'string' ? { min: field.def.earliest } : {})}
        {...(typeof field.def.latest === 'string' ? { max: field.def.latest } : {})}
        value={typeof field.value === 'string' ? field.value : ''}
        onChange={(event) => field.setValue(event.target.value === '' ? null : event.target.value)}
        onBlur={() => field.touch()}
      />
    </FieldShell>
  )
}

/**
 * An instant, stored as `YYYY-MM-DDTHH:MM:SSZ`.
 *
 * `<input type="datetime-local">` because there is no zoned datetime input in any
 * browser — so the control shows the reader a local wall clock and this converts.
 * The conversion is the whole reason this component exists rather than reusing
 * `DateField`:
 *
 * - **In:** the control gives `YYYY-MM-DDTHH:MM` in the reader's own zone. `new
 *   Date(local).toISOString()` interprets a zoneless string as local time, which is
 *   what is wanted here and is exactly what `bindTimestamp` refuses for a stored
 *   value — the difference is that the reader's zone is known at the moment they
 *   type, and is not knowable later.
 * - **Out:** the stored instant is rendered back into local time for the control,
 *   sliced to minutes because the input rejects a seconds component it was not asked
 *   for.
 *
 * Seconds are therefore always `00` in an answer a person typed. The format keeps
 * them because a machine-supplied answer has them and a fixed width is what makes
 * ordering work.
 */
export function DateTimeField({ path, label }: FieldComponentProps) {
  const field = useField(path)
  const stored = typeof field.value === 'string' ? field.value : ''
  const asLocal = (): string => {
    if (stored === '') return ''
    const instant = new Date(stored)
    if (Number.isNaN(instant.getTime())) return ''
    // Local parts, not `toISOString()`: that would show UTC in a control the
    // browser labels as local, so the reader would see an hour they did not type.
    const pad = (part: number): string => String(part).padStart(2, '0')
    return (
      `${String(instant.getFullYear())}-${pad(instant.getMonth() + 1)}-${pad(instant.getDate())}` +
      `T${pad(instant.getHours())}:${pad(instant.getMinutes())}`
    )
  }

  return (
    <FieldShell path={path} field={field} label={label}>
      <input
        type="datetime-local"
        {...field.controlProps}
        value={asLocal()}
        onChange={(event) => {
          const local = event.target.value
          if (local === '') {
            field.setValue(null)
            return
          }
          const instant = new Date(local)
          // A control can hand back something unparseable mid-edit. Writing null
          // rather than a malformed string keeps the stored answer always either
          // empty or canonical, which is what the engine's shape check assumes.
          field.setValue(
            Number.isNaN(instant.getTime())
              ? null
              : `${instant.toISOString().slice(0, 19)}Z`,
          )
        }}
        onBlur={() => field.touch()}
      />
    </FieldShell>
  )
}

// packages/angular/src/fields/temporal-fields.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core'
import { FieldComponentBase, FormancyFieldShell } from './field-shell.js'


/**
 * The temporal controls, each holding one canonical fixed-width string.
 *
 * One file per control, because a control changes for its own reasons.
 * These were one 1,909-line file — the second largest in the repository,
 * and the place things went.
 */
@Component({
  selector: 'formancy-date-field',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormancyFieldShell],
  template: `
    <formancy-field-shell [field]="field" [label]="context.label" [path]="context.path">
      <input
        type="date"
        [id]="control().id"
        [attr.name]="control().name"
        [attr.aria-invalid]="control()['aria-invalid']"
        [attr.aria-required]="control()['aria-required']"
        [attr.aria-describedby]="control()['aria-describedby']"
        [disabled]="control().disabled === true"
        [value]="text()"
        (input)="onInput($event)"
        (blur)="field.touch()"
      />
    </formancy-field-shell>
  `,
})
export class FormancyDateField extends FieldComponentBase {
  protected readonly text = computed(() => {
    const value = this.field.snapshot().value
    return typeof value === 'string' ? value : ''
  })

  protected onInput(event: Event): void {
    const raw = (event.target as HTMLInputElement).value
    this.field.setValue(raw === '' ? null : raw)
  }
}

@Component({
  selector: 'formancy-time-field',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormancyFieldShell],
  template: `
    <formancy-field-shell [field]="field" [label]="context.label" [path]="context.path">
      <input
        type="time"
        [id]="control().id"
        [attr.name]="control().name"
        [attr.aria-invalid]="control()['aria-invalid']"
        [attr.aria-required]="control()['aria-required']"
        [attr.aria-describedby]="control()['aria-describedby']"
        [attr.min]="earliest()"
        [attr.max]="latest()"
        [disabled]="control().disabled === true"
        [value]="text()"
        (input)="onInput($event)"
        (blur)="field.touch()"
      />
    </formancy-field-shell>
  `,
})
/**
 * A time of day, as `HH:MM`.
 *
 * `<input type="time">` gives the platform's picker, keyboard handling and locale
 * display — a 12-hour clock where the reader expects one — while its `value` is
 * always 24-hour `HH:MM`. Exactly the split the format wants: the reader sees their
 * convention, the answer records one canonical shape.
 *
 * No `step`, so the browser offers no seconds. A time answer has none, and a control
 * offering precision the format discards loses what somebody typed.
 */
export class FormancyTimeField extends FieldComponentBase {
  protected readonly text = computed(() => {
    const value = this.field.snapshot().value
    return typeof value === 'string' ? value : ''
  })

  /* Bounds handed to the browser as well as checked by the engine. The engine's
     check is the truth — it runs again on the server — and these let the platform
     grey out what it will not accept, which beats a message after the fact. */
  protected readonly earliest = computed(() => {
    const bound = this.field.snapshot().def.earliest
    return typeof bound === 'string' ? bound : null
  })

  protected readonly latest = computed(() => {
    const bound = this.field.snapshot().def.latest
    return typeof bound === 'string' ? bound : null
  })

  protected onInput(event: Event): void {
    const raw = (event.target as HTMLInputElement).value
    this.field.setValue(raw === '' ? null : raw)
  }
}

@Component({
  selector: 'formancy-datetime-field',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormancyFieldShell],
  template: `
    <formancy-field-shell [field]="field" [label]="context.label" [path]="context.path">
      <input
        type="datetime-local"
        [id]="control().id"
        [attr.name]="control().name"
        [attr.aria-invalid]="control()['aria-invalid']"
        [attr.aria-required]="control()['aria-required']"
        [attr.aria-describedby]="control()['aria-describedby']"
        [disabled]="control().disabled === true"
        [value]="localText()"
        (input)="onInput($event)"
        (blur)="field.touch()"
      />
    </formancy-field-shell>
  `,
})
/**
 * An instant, stored as `YYYY-MM-DDTHH:MM:SSZ`.
 *
 * `datetime-local` because no browser has a zoned datetime input, so the control
 * shows a local wall clock and this converts. The conversion is why this is not the
 * date field with another `type`:
 *
 * - **In:** the control gives `YYYY-MM-DDTHH:MM` in the reader's own zone, and `new
 *   Date(local)` reads a zoneless string as local time — which is what is wanted at
 *   the moment somebody types, and exactly what `bindTimestamp` refuses for a value
 *   already stored, because the zone is not knowable later.
 * - **Out:** the stored instant is rendered back into local parts for the control,
 *   never `toISOString()`, which would show UTC in a box the browser labels local.
 *
 * Seconds are therefore `00` in any answer a person typed. The format keeps them
 * because a machine-supplied answer has them, and one fixed width is what makes
 * ordering work.
 */
export class FormancyDateTimeField extends FieldComponentBase {
  protected readonly localText = computed(() => {
    const value = this.field.snapshot().value
    if (typeof value !== 'string' || value === '') return ''
    const instant = new Date(value)
    if (Number.isNaN(instant.getTime())) return ''
    const pad = (part: number): string => String(part).padStart(2, '0')
    return (
      `${String(instant.getFullYear())}-${pad(instant.getMonth() + 1)}-${pad(instant.getDate())}` +
      `T${pad(instant.getHours())}:${pad(instant.getMinutes())}`
    )
  })

  protected onInput(event: Event): void {
    const local = (event.target as HTMLInputElement).value
    if (local === '') {
      this.field.setValue(null)
      return
    }
    const instant = new Date(local)
    // A control can hand back something unparseable mid-edit. Null rather than a
    // malformed string keeps the stored answer always either empty or canonical,
    // which is what the engine's shape check assumes.
    this.field.setValue(
      Number.isNaN(instant.getTime()) ? null : `${instant.toISOString().slice(0, 19)}Z`,
    )
  }
}
