// packages/react/src/fields/text-fields.tsx
import { useState } from 'react'
import { answerFromText, editMasked, formatMasked, maskIsNumeric, maskPlaceholder } from '@formancy/spec'
import { useFormText } from '../context.js'
import { useField } from '../use-field.js'
import { useScanner } from '../scanning.js'
import { FieldShell } from './internals.js'
import type { FieldComponentProps } from './internals.js'


/**
 * The controls that take typed text, and the widgets over them.
 *
 * One file per control, because a control changes for its own reasons.
 * These were one 2,154-line file — the largest in the repository.
 */
/**
 * A single-line answer, and — with `widget: "scanner"` — a camera route to the same
 * string.
 *
 * The input is the control in both cases, never a second one beside it: typing is
 * the accessibility floor and the fallback at once, so it is what is always there
 * and the scan button is what is sometimes added. With no scanner supplied the
 * markup is the default control exactly, because a Scan button that opens nothing is
 * worse than no button ([0071](../../../docs/decisions/0071-a-scanner-is-supplied-not-built.md)).
 */
export function TextField({ path, label }: FieldComponentProps) {
  const field = useField(path)
  const scan = useScanner()
  const words = useFormText()
  const [scanning, setScanning] = useState(false)
  /**
   * A device failure, held here rather than in the field's errors. See below. What went
   * wrong rather than a sentence about it, so the sentence is the form's language's.
   */
  const [trouble, setTrouble] = useState<{ reason?: string } | undefined>(undefined)

  /**
   * The ONE place a text field's answer is written, typed or scanned.
   *
   * Structural rather than careful: the parameter is a `string`, so there is no path
   * from the camera to `setValue` that could store something typing could not. That
   * is the line a widget may never cross — it changes how a field looks, never what
   * it collects ([0065](../../../docs/decisions/0065-a-widget-is-authored-not-registered.md)).
   */
  const commit = (text: string): void =>
    // `<input type="text">` runs the platform's value sanitiser on everything that reaches
    // it -- "strip newlines from the value", in HTML's value sanitization algorithm -- so a
    // typed or pasted answer can never hold CR or LF. A scanned code CAN: a Wi-Fi or vCard
    // payload is several lines. Applying the control's own rule here is what makes a scanned
    // answer byte-identical to a typed one rather than merely similar, which is the line a
    // widget may not cross
    // ([0065](../../../docs/decisions/0065-a-widget-is-authored-not-registered.md)).
    //
    // Not a second validator -- `pattern` stays the engine's -- and not taste: jsdom does
    // not implement the sanitiser either, so nothing here notices unless it is asserted.
    field.setValue(text.replace(/[\r\n]/g, ''))

  /*
   * With a mask, the control shows the answer in its shape and the answer holds only
   * what was typed into the positions. Where a typed, deleted or pasted character
   * lands is `editMasked`'s, in `@formancy/spec`, which the Angular binding calls too —
   * two answers to one keystroke would be the drift 0091 exists to prevent (0125).
   */
  const mask = field.def.mask
  const answer = typeof field.value === 'string' ? field.value : ''
  const shown = mask === undefined ? answer : formatMasked(mask, answer)

  const read = async (): Promise<void> => {
    // Re-entrancy, which `disabled` used to prevent: a second press while a scan is in
    // flight is ignored rather than opening a second camera session.
    if (scan === undefined || scanning) return
    setScanning(true)
    setTrouble(undefined)
    try {
      const text = await scan({ label, path })
      // Nobody scanned anything: the sheet was closed, or they changed their mind.
      // Not a failure, and an apology in a live region for a decision somebody made
      // on purpose is noise.
      if (text === null) return
      if (typeof text !== 'string') {
        // A host written in plain JavaScript can resolve with anything. Reported as
        // the device failure it is, rather than stored — an object in a text field
        // is exactly what `commit` exists to make impossible.
        setTrouble({})
        return
      }
      // Stored as typed, THEN touched — so a value the field's `pattern` refuses
      // shows the engine's own error rather than being dropped. Dropping it would
      // discard the only record of what the camera read and leave the field looking
      // empty, which is the worse of the two failures by some distance. A masked
      // field reads it the way it reads a paste.
      commit(mask === undefined ? text : answerFromText(mask, text))
      field.touch()
    } catch (error) {
      setTrouble({ reason: error instanceof Error ? error.message : String(error) })
    } finally {
      setScanning(false)
    }
  }

  return (
    <FieldShell path={path} field={field} label={label}>
      <input
        type="text"
        {...field.controlProps}
        value={shown}
        // The shape as the hint, and a keypad when every position takes a digit.
        placeholder={mask === undefined ? undefined : maskPlaceholder(mask)}
        inputMode={mask !== undefined && maskIsNumeric(mask) ? 'numeric' : undefined}
        onChange={(event) => {
          if (mask === undefined) {
            commit(event.target.value)
            return
          }
          const input = event.target
          const forward = (event.nativeEvent as InputEvent).inputType === 'deleteContentForward'
          const edit = editMasked(mask, answer, input.value, {
            caret: input.selectionStart,
            direction: forward ? 'forward' : 'backward',
          })
          // Written to the control before React renders, so the caret can be placed in
          // the text it belongs to: React would write the same text a moment later and
          // leave the caret at its end. (A refused character React removes by itself,
          // restoring the controlled value — measured, not assumed.)
          input.value = formatMasked(mask, edit.answer)
          input.setSelectionRange(edit.caret, edit.caret)
          commit(edit.answer)
        }}
        onBlur={() => field.touch()}
      />
      {field.def.widget === 'scanner' && scan !== undefined ? (
        <>
          <button
            type="button"
            data-formancy-part="scanner-button"
            // Disabled only when the FIELD is. Disabling the button somebody just pressed
            // blurs it, and the browser then resets focus to `<body>` — so a keyboard user
            // who presses Scan is returned to the top of the document, and the status line
            // tells them to type the value instead into a field they now have to find again.
            //
            // Busy is said with `aria-busy`, which changes nothing about focus, and the guard
            // in `read` does what `disabled` was doing. Not testable here: jsdom does not
            // blur a focused element that becomes disabled, which is exactly why this was
            // written the other way round first.
            disabled={field.disabled}
            aria-busy={scanning ? true : undefined}
            onClick={() => {
              void read()
            }}
          >
            {/* The word is the visible label and the field's name completes the
                accessible one, so three scannable fields on a page do not offer
                three buttons called "Scan" — and the visible text is still
                contained in the accessible name (WCAG 2.5.3). */}
            {words('scanner.scan')} <span data-formancy-part="visually-hidden">{label}</span>
          </button>
          {/* The camera's own progress and its failures, in this field's polite
              region. NOT the error region: that one is the control's describedby
              target, it holds the engine's verdicts, and a refused permission put
              there would describe a hardware problem as a wrong answer. Same shape
              as the file field's status line, for the same reason. */}
          <p role="status" data-formancy-part="scanner-status">
            {scanning
              ? words('scanner.scanning')
              : trouble === undefined
                ? ''
                : trouble.reason === undefined
                  ? words('scanner.noText')
                  : words('scanner.failed', { reason: trouble.reason })}
          </p>
        </>
      ) : null}
    </FieldShell>
  )
}

export function TextareaField({ path, label }: FieldComponentProps) {
  const field = useField(path)
  return (
    <FieldShell path={path} field={field} label={label}>
      <textarea
        {...field.controlProps}
        value={typeof field.value === 'string' ? field.value : ''}
        onChange={(event) => field.setValue(event.target.value)}
        onBlur={() => field.touch()}
      />
    </FieldShell>
  )
}

export function NumberField({ path, label }: FieldComponentProps) {
  const field = useField(path)
  return (
    <FieldShell path={path} field={field} label={label}>
      <input
        type="number"
        {...field.controlProps}
        value={typeof field.value === 'number' ? field.value : ''}
        onChange={(event) =>
          field.setValue(event.target.value === '' ? null : event.target.valueAsNumber)
        }
        onBlur={() => field.touch()}
      />
    </FieldShell>
  )
}

// packages/angular/src/fields/text-fields.ts
import { ChangeDetectionStrategy, Component, computed, input, signal } from '@angular/core'
import type { Type } from '@angular/core'
import { answerFromText, editMasked, formatMasked, maskIsNumeric, maskPlaceholder } from '@formancy/spec'
import { injectScanner } from '../scanning.js'
import { FormancyTextPipe, injectFormText } from '../text.js'
import { FieldComponentBase, FormancyFieldShell } from './field-shell.js'


/**
 * The controls that take typed text, and the widgets over them.
 *
 * One file per control, because a control changes for its own reasons.
 * These were one 1,909-line file — the second largest in the repository,
 * and the place things went.
 */
/**
 * A single-line answer, and — with `widget: "scanner"` — a camera route to the same
 * string.
 *
 * The input is the control in both cases, never a second one beside it: typing is the
 * accessibility floor and the fallback at once, so it is what is always there and the
 * scan button is what is sometimes added. With no scanner supplied the markup is the
 * default control exactly, because a Scan button that opens nothing is worse than no
 * button ([0071](../../../docs/decisions/0071-a-scanner-is-supplied-not-built.md)).
 *
 * The React binding renders the same three elements for the same reasons.
 */
@Component({
  selector: 'formancy-text-field',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormancyFieldShell, FormancyTextPipe],
  template: `
    <formancy-field-shell [field]="field" [label]="context.label" [path]="context.path">
      <input
        type="text"
        [id]="control().id"
        [attr.name]="control().name"
        [attr.aria-invalid]="control()['aria-invalid']"
        [attr.aria-required]="control()['aria-required']"
        [attr.aria-describedby]="control()['aria-describedby']"
        [disabled]="control().disabled === true"
        [value]="text()"
        [attr.placeholder]="placeholder()"
        [attr.inputmode]="inputMode()"
        (input)="onInput($event)"
        (blur)="field.touch()"
      />
      @if (scannable()) {
        <!-- The word is the visible label and the field's name completes the
             accessible one, so three scannable fields on a page do not offer three
             buttons called "Scan" — and the visible text is still contained in the
             accessible name (WCAG 2.5.3). One line, because element-internal
             whitespace leaks into the accessible name. -->
        <!-- Disabled only when the FIELD is, never while scanning: disabling the button
             somebody just pressed blurs it and the browser resets focus to the document
             body, so a keyboard user is returned to the top of the page and told to type
             instead into a field they must find again. Busy is said with aria-busy, which
             does not touch focus, and the guard in read() does what disabled was doing.
             Kept on one line because element-internal whitespace leaks into the accessible
             name. -->
        <button type="button" data-formancy-part="scanner-button" [disabled]="field.snapshot().disabled" [attr.aria-busy]="scanning() ? 'true' : null" (click)="read()">{{ 'scanner.scan' | formancyText }} <span data-formancy-part="visually-hidden">{{ context.label }}</span></button>
        <!-- The camera's own progress and its failures, in this field's polite
             region. NOT the error region: that one is the control's describedby
             target, it holds the engine's verdicts, and a refused permission put
             there would describe a hardware problem as a wrong answer. The same
             shape the file field uses for an upload. -->
        <p role="status" data-formancy-part="scanner-status">{{ status() }}</p>
      }
    </formancy-field-shell>
  `,
})
export class FormancyTextField extends FieldComponentBase {
  private readonly scan = injectScanner()
  protected readonly scanning = signal(false)
  /** A device failure, held here rather than in the field's errors. See above. */
  /**
   * A device failure: what went wrong rather than a sentence about it, so the sentence is
   * the form's language's (0171). No reason is a scanner that answered with something
   * other than text.
   */
  private readonly trouble = signal<{ reason?: string } | undefined>(undefined)
  private readonly words = injectFormText()

  /**
   * The answer, and with a mask the answer in its shape. Where a typed, deleted or
   * pasted character lands is `editMasked`'s, in `@formancy/spec`, which the React
   * binding calls too — two answers to one keystroke would be the drift 0091 exists to
   * prevent (0125).
   */
  private readonly mask = computed(() => this.field.snapshot().def.mask)
  private readonly answer = computed(() => {
    const value = this.field.snapshot().value
    return typeof value === 'string' ? value : ''
  })
  protected readonly text = computed(() => {
    const mask = this.mask()
    return mask === undefined ? this.answer() : formatMasked(mask, this.answer())
  })
  /** The shape as the hint, and a keypad when every position takes a digit. */
  protected readonly placeholder = computed(() => {
    const mask = this.mask()
    return mask === undefined ? null : maskPlaceholder(mask)
  })
  protected readonly inputMode = computed(() => {
    const mask = this.mask()
    return mask !== undefined && maskIsNumeric(mask) ? 'numeric' : null
  })

  /**
   * A computed over the field's SIGNAL, not over `engine.getFieldSnapshot` — the
   * widget can arrive with a new document, and a plain method call is not a
   * dependency an OnPush component re-runs for.
   */
  protected readonly scannable = computed(
    () => this.scan !== null && this.field.snapshot().def.widget === 'scanner',
  )

  protected readonly status = computed(() => {
    if (this.scanning()) return this.words('scanner.scanning')
    const trouble = this.trouble()
    if (trouble === undefined) return ''
    return trouble.reason === undefined
      ? this.words('scanner.noText')
      : this.words('scanner.failed', { reason: trouble.reason })
  })

  protected onInput(event: Event): void {
    const input = event.target as HTMLInputElement
    const mask = this.mask()
    if (mask === undefined) {
      this.commit(input.value)
      return
    }
    const forward = (event as InputEvent).inputType === 'deleteContentForward'
    const edit = editMasked(mask, this.answer(), input.value, {
      caret: input.selectionStart,
      direction: forward ? 'forward' : 'backward',
    })
    // Written to the control here rather than left to the binding: a refused character
    // leaves the answer — and so `text()` — unchanged, and Angular writes a bound value
    // only when it changes, so the character would stay on screen. And the caret can
    // only be placed in text that is already there.
    input.value = formatMasked(mask, edit.answer)
    input.setSelectionRange(edit.caret, edit.caret)
    this.commit(edit.answer)
  }

  /**
   * The ONE place a text field's answer is written, typed or scanned.
   *
   * Structural rather than careful: the parameter is a `string`, so there is no path
   * from the camera to `setValue` that could store something typing could not — the
   * line a widget may never cross
   * ([0065](../../../docs/decisions/0065-a-widget-is-authored-not-registered.md)).
   */
  private commit(text: string): void {
    // See the React binding: `<input type="text">` strips CR and LF from anything typed or
    // pasted, so a multi-line code payload stored verbatim would be an answer the default
    // control cannot produce -- the one thing a widget may never do.
    this.field.setValue(text.replace(/[\r\n]/g, ''))
  }

  protected async read(): Promise<void> {
    // Re-entrancy, which `disabled` used to prevent: a second press while a scan is in
    // flight is ignored rather than opening a second camera session.
    if (this.scan === null || this.scanning()) return
    this.scanning.set(true)
    this.trouble.set(undefined)
    try {
      const text = await this.scan({ label: this.context.label, path: this.context.path })
      // Nobody scanned anything: the sheet was closed, or they changed their mind.
      // Not a failure, and an apology in a live region for a decision somebody made
      // on purpose is noise.
      if (text === null) return
      if (typeof text !== 'string') {
        // A host written in plain JavaScript can resolve with anything. Reported as
        // the device failure it is, rather than stored — an object in a text field is
        // exactly what `commit` exists to make impossible.
        this.trouble.set({})
        return
      }
      // Stored as typed, THEN touched — so a value the field's `pattern` refuses
      // shows the engine's own error rather than being dropped. Dropping it would
      // discard the only record of what the camera read and leave the field looking
      // empty, which is the worse of the two failures by some distance. A masked
      // field reads it the way it reads a paste.
      const mask = this.mask()
      this.commit(mask === undefined ? text : answerFromText(mask, text))
      this.field.touch()
    } catch (error) {
      this.trouble.set({ reason: error instanceof Error ? error.message : String(error) })
    } finally {
      this.scanning.set(false)
    }
  }
}

@Component({
  selector: 'formancy-textarea-field',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormancyFieldShell],
  template: `
    <formancy-field-shell [field]="field" [label]="context.label" [path]="context.path">
      <textarea
        [id]="control().id"
        [attr.name]="control().name"
        [attr.aria-invalid]="control()['aria-invalid']"
        [attr.aria-required]="control()['aria-required']"
        [attr.aria-describedby]="control()['aria-describedby']"
        [disabled]="control().disabled === true"
        [value]="text()"
        (input)="onInput($event)"
        (blur)="field.touch()"
      ></textarea>
    </formancy-field-shell>
  `,
})
export class FormancyTextareaField extends FieldComponentBase {
  protected readonly text = computed(() => {
    const value = this.field.snapshot().value
    return typeof value === 'string' ? value : ''
  })

  protected onInput(event: Event): void {
    this.field.setValue((event.target as HTMLTextAreaElement).value)
  }
}
