// packages/angular/src/fields/signature-field.ts
import { ChangeDetectionStrategy, Component, computed, input, viewChild } from '@angular/core'
import type { ElementRef, Type } from '@angular/core'
import { FieldComponentBase, FormancyFieldShell } from './field-shell.js'


/**
 * The signature control: a mark drawn, or a name typed.
 *
 * One file per control, because a control changes for its own reasons.
 * These were one 1,909-line file — the second largest in the repository,
 * and the place things went.
 */
/**
 * Sign here: draw a mark, or type your name.
 *
 * The same control as the React one, part for part, because a theme dresses both
 * through the same `data-formancy-part` names and a renderer that emitted
 * different ones would need its own stylesheet
 * ([0083](../../../docs/decisions/0083-a-signature-is-points-or-a-name.md)).
 *
 * Typing is the keyboard route and is not a lesser one: a field offering drawing
 * alone would be a WCAG 2.1.1 failure with a legal signature attached to it.
 * SVG rather than canvas because the answer is points, and points can be drawn
 * declaratively — a canvas would hold pixels the answer does not contain.
 */
@Component({
  selector: 'formancy-signature-field',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormancyFieldShell],
  template: `
    <formancy-field-shell [field]="field" [label]="context.label" [path]="context.path">
      <div data-formancy-part="signature">
        <svg
          #surface
          data-formancy-part="signature-surface"
          style="touch-action: none"
          [attr.viewBox]="viewBox()"
          role="img"
          [attr.aria-label]="context.label"
          (pointerdown)="onDown($event)"
          (pointermove)="onMove($event)"
          (pointerup)="onUp()"
          (pointerleave)="onUp()"
          (touchstart)="noScroll($event)"
          (touchmove)="noScroll($event)"
        >
          @for (stroke of strokes(); track $index) {
            <path data-formancy-part="signature-stroke" [attr.d]="pathOf(stroke)" fill="none" />
          }
        </svg>

        <input
          data-formancy-part="signature-typed"
          type="text"
          aria-label="Type your name"
          [value]="typed()"
          (input)="onTyped($event)"
          (blur)="field.touch()"
        />

        <button data-formancy-part="signature-clear" type="button" (click)="clear()">Clear</button>
      </div>
    </formancy-field-shell>
  `,
})
export class FormancySignatureField extends FieldComponentBase {
  private readonly surface = viewChild<ElementRef<SVGSVGElement>>('surface')
  private stroke: Array<[number, number]> | null = null
  /** The strokes finished before this one started. Held rather than read back
   *  from the value, which already contains the stroke in progress — reading it
   *  made every pointer move append another stroke, so one signature came out as
   *  forty of a single point each. */
  private before: Array<Array<[number, number]>> = []

  private readonly answer = computed(() => {
    const value = this.field.snapshot().value
    return (typeof value === 'object' && value !== null ? value : {}) as {
      drawn?: Array<Array<[number, number]>>
      typed?: string
    }
  })

  protected readonly strokes = computed(() => this.answer().drawn ?? [])
  protected readonly typed = computed(() => this.answer().typed ?? '')
  private readonly box = computed<[number, number]>(() => this.field.snapshot().def.box ?? [600, 200])
  protected readonly viewBox = computed(() => `0 0 ${String(this.box()[0])} ${String(this.box()[1])}`)

  protected pathOf(points: ReadonlyArray<readonly [number, number]>): string {
    return points
      .map(([x, y], step) => `${step === 0 ? 'M' : 'L'}${String(x)} ${String(y)}`)
      .join(' ')
  }

  /*
   * A touch drag on this surface is a signature, not a scroll.
   *
   * Reported from an iPad: the control is unusable because the page scrolls
   * while you sign. `touch-action: none` on the surface is the mechanism, and it
   * has to be resolved in the compositor before the first event arrives -- by
   * the time this class runs, the browser has already decided. It was only in
   * the four themes until now, which is why drawing worked everywhere the demo
   * was looked at and nowhere else; this package ships no CSS, so what the
   * control needs in order to *work* belongs to the control. Appearance -- a
   * height, a border, a cursor -- is still the theme's.
   *
   * This method is the fallback for a browser that did not honour the property,
   * which is the case that cannot be tested from here. Where it is honoured the
   * event is not cancelable and this costs nothing.
   *
   * **A template binding, where the React control attaches listeners by hand.**
   * Angular's `(touchmove)` goes through `addEventListener` on the element,
   * which is non-passive by default; React registers `touchstart` and
   * `touchmove` at the root and marks them passive, where `preventDefault` is
   * ignored. Same decision, each framework's idiom -- not a difference to tidy
   * away.
   */
  protected noScroll(event: TouchEvent): void {
    // `cancelable` is checked because Chrome logs "Ignored attempt to cancel a
    // touchmove event with cancelable=false" otherwise -- which is what arrives
    // when `touch-action` WAS honoured, so the common case would print a warning
    // per finger move. **No test covers this branch**: jsdom emits no such
    // warning and `defaultPrevented` reads false either way, so the mutation
    // survives the suite. Kept on the strength of the browser behaviour, and
    // said out loud rather than left looking verified.
    if (event.cancelable) event.preventDefault()
  }

  protected onDown(event: PointerEvent): void {
    this.before = [...this.strokes()]
    this.stroke = [this.pointFrom(event)]
    this.surface()?.nativeElement.setPointerCapture?.(event.pointerId)
  }

  protected onMove(event: PointerEvent): void {
    if (this.stroke === null) return
    this.stroke = [...this.stroke, this.pointFrom(event)]
    this.commit([...this.before, this.stroke])
  }

  protected onUp(): void {
    const finished = this.stroke
    // Nothing in progress, so nothing to end. `pointerleave` shares this handler
    // — which is what ends a stroke whose pen went past the edge without ever
    // sending `pointerup` here — and it fires AGAIN once the pen has already
    // lifted, when `before` holds the strokes from before the last one. Falling
    // through to `commit(before)` then threw away the stroke just drawn.
    //
    // Measured in the built playground, because the sequence every test here used
    // was down, move, up — and the thing a person does next is move their hand
    // away: one stroke on screen after the button came up, and none once the
    // mouse left the box.
    if (finished === null) return
    this.stroke = null
    // One point is a tap on the way past, not a signature.
    if (finished.length < 2) this.commit(this.before)
  }

  protected onTyped(event: Event): void {
    const typed = (event.target as HTMLInputElement).value
    this.field.setValue(typed === '' ? null : { typed })
  }

  protected clear(): void {
    this.stroke = null
    this.before = []
    this.field.setValue(null)
  }

  /** A client point in the field's own space, whole-numbered and clamped. */
  private pointFrom(event: PointerEvent): [number, number] {
    const rect = this.surface()?.nativeElement.getBoundingClientRect()
    const [width, height] = this.box()
    const scaleX = rect === undefined || rect.width === 0 ? 1 : width / rect.width
    const scaleY = rect === undefined || rect.height === 0 ? 1 : height / rect.height
    const x = (event.clientX - (rect?.left ?? 0)) * scaleX
    const y = (event.clientY - (rect?.top ?? 0)) * scaleY
    return [
      Math.max(0, Math.min(width, Math.round(x))),
      Math.max(0, Math.min(height, Math.round(y))),
    ]
  }

  /** Nothing drawn is `null`, never `{ drawn: [] }`: an empty mark presented as
   *  an answer is what would satisfy a required signature with no signature. */
  private commit(strokes: Array<Array<[number, number]>>): void {
    this.field.setValue(strokes.length === 0 ? null : { drawn: strokes })
  }
}

// packages/react/src/fields/signature-field.tsx
import { useEffect, useRef } from 'react'
import { useField } from '../use-field.js'
import { FieldShell } from './internals.js'
import type { FieldComponentProps, SignatureAnswerValue } from './internals.js'


/**
 * The signature control: a mark drawn, or a name typed.
 *
 * One file per control, because a control changes for its own reasons.
 * These were one 2,154-line file — the largest in the repository.
 */
/**
 * Sign here: draw a mark, or type your name.
 *
 * **Both routes are the feature, not a fallback and its apology.** Typing your
 * name is how most people sign most things, and it is the only route a keyboard
 * has — a field that offered drawing alone would be a WCAG 2.1.1 failure with a
 * legal signature attached to it. So the two sit side by side and the last one
 * used is the answer; they are never both present, because a reader choosing
 * between them is a signed document that renders differently depending on the
 * choice.
 *
 * **SVG, not canvas.** A canvas answer would be pixels, and this stores points
 * ([0083](../../../docs/decisions/0083-a-signature-is-points-or-a-name.md)):
 * points scale, diff, survive a re-render and mean something to a reader that is
 * not a browser. Drawing them as an SVG path costs nothing extra and makes the
 * mark visible to anything that can read the DOM, including a test.
 *
 * **No stroke timing.** Velocity is what makes a signature biometric, and
 * biometric data is a category (GDPR Article 9) nothing here is equipped to
 * hold.
 */
export function SignatureField({ path, label }: FieldComponentProps) {
  const field = useField(path)
  const answer = (typeof field.value === 'object' && field.value !== null
    ? field.value
    : {}) as SignatureAnswerValue
  const drawn = answer.drawn ?? []
  const [width, height] = field.def?.box ?? [600, 200]

  const surface = useRef<SVGSVGElement | null>(null)
  const stroke = useRef<Array<[number, number]> | null>(null)
  /**
   * The strokes finished before this one started.
   *
   * Held rather than read back from the value, which is what the first version
   * did — and the value already contains the stroke in progress, so every move
   * appended another one. A signature drawn in the playground came out as forty
   * strokes of a single point each; the unit tests moved once per stroke, which
   * is the one shape that cannot show it.
   */
  const before = useRef<Array<Array<[number, number]>>>([])

  /**
   * A client point in the field's own coordinate space, rounded to whole numbers.
   *
   * Whole numbers because the canonical hash a submission is bound to must not
   * depend on how a browser rounded a pointer event. Clamped, because a pointer
   * that leaves the box mid-stroke would otherwise record a point the engine
   * refuses — the answer being invalid is the right outcome for a hand-written
   * payload and the wrong one for somebody whose hand went past the edge.
   */
  const pointFrom = (event: { clientX: number; clientY: number }): [number, number] => {
    const rect = surface.current?.getBoundingClientRect()
    // jsdom, and anything else that has not laid out yet, measures zero. Falling
    // back to the raw offset keeps the stroke recordable rather than dividing by
    // nothing.
    const scaleX = rect === undefined || rect.width === 0 ? 1 : width / rect.width
    const scaleY = rect === undefined || rect.height === 0 ? 1 : height / rect.height
    const x = (event.clientX - (rect?.left ?? 0)) * scaleX
    const y = (event.clientY - (rect?.top ?? 0)) * scaleY
    return [
      Math.max(0, Math.min(width, Math.round(x))),
      Math.max(0, Math.min(height, Math.round(y))),
    ]
  }

  const commit = (strokes: Array<Array<[number, number]>>): void => {
    // Nothing drawn is NOT `{ drawn: [] }`: an empty mark presented as an answer
    // is what would let a required signature be satisfied by signing nothing.
    field.setValue(strokes.length === 0 ? null : { drawn: strokes })
  }

  /*
   * A touch drag on this surface is a signature, not a scroll.
   *
   * Reported from an iPad: the control is unusable because the page scrolls
   * while you sign. `touch-action: none` is how an element resolves that
   * ambiguity, and it has to be resolved in the compositor before the first
   * event arrives — by the time a handler runs, the browser has already decided.
   *
   * It was only in the four themes, which is why drawing worked everywhere the
   * demo was looked at and nowhere else. Measured in Chromium with the theme
   * removed: `auto` on the surface, inside a pane whose overflow is `auto`, so a
   * finger pans the pane. This package ships no CSS at all, so anything the
   * control needs in order to *work* belongs to the control. Appearance still
   * belongs to the consumer: a height, a border and a cursor are the theme's.
   *
   * Inline, which is heavy-handed and deliberate — a consumer who overrode this
   * would be turning the control off.
   */
  const preventsScroll = { touchAction: 'none' } as const

  /*
   * And prevented by hand as well, for a browser that did not honour the above.
   *
   * The device this was reported on cannot be driven from here, and the property
   * was already doing its job in the one that can be — so the honest position is
   * that the primary mechanism is verified and this is the fallback for the case
   * that is not. Where it is honoured these events are not cancelable and this
   * costs nothing.
   *
   * By hand rather than `onTouchMove`, because React registers `touchstart` and
   * `touchmove` at the root as **passive**, where `preventDefault` is ignored
   * and logs a warning. A passive handler would look exactly like a fix and do
   * nothing.
   */
  useEffect(() => {
    const element = surface.current
    if (element === null) return

    const swallow = (event: TouchEvent): void => {
    // `cancelable` is checked because Chrome logs "Ignored attempt to cancel a
    // touchmove event with cancelable=false" otherwise -- which is what arrives
    // when `touch-action` WAS honoured, so the common case would print a warning
    // per finger move. **No test covers this branch**: jsdom emits no such
    // warning and `defaultPrevented` reads false either way, so the mutation
    // survives the suite. Kept on the strength of the browser behaviour, and
    // said out loud rather than left looking verified.
      if (event.cancelable) event.preventDefault()
    }
    element.addEventListener('touchstart', swallow, { passive: false })
    element.addEventListener('touchmove', swallow, { passive: false })
    return () => {
      element.removeEventListener('touchstart', swallow)
      element.removeEventListener('touchmove', swallow)
    }
  }, [])

  const onPointerDown = (event: React.PointerEvent<SVGSVGElement>): void => {
    before.current = drawn
    stroke.current = [pointFrom(event)]
    // Not in jsdom, and not on a mouse that never left the element.
    surface.current?.setPointerCapture?.(event.pointerId)
  }

  const onPointerMove = (event: React.PointerEvent<SVGSVGElement>): void => {
    if (stroke.current === null) return
    stroke.current = [...stroke.current, pointFrom(event)]
    // Drawn as it goes: a mark that only appears when the pen lifts reads as a
    // surface that is not listening.
    commit([...before.current, stroke.current])
  }

  const onPointerUp = (): void => {
    const finished = stroke.current
    // Nothing in progress, so nothing to end. `pointerleave` shares this handler
    // — which is what ends a stroke whose pen went past the edge without ever
    // sending `pointerup` here — and it fires AGAIN once the pen has already
    // lifted, when `before` holds the strokes from before the last one. Falling
    // through to `commit(before)` then threw away the stroke just drawn.
    //
    // Measured in the built playground, because the sequence every test here used
    // was down, move, up — and the thing a person does next is move their hand
    // away: one stroke on screen after the button came up, and none once the
    // mouse left the box.
    if (finished === null) return
    stroke.current = null
    // One point is a tap, not a stroke, and a tap on the way past should not
    // count as having signed — so the strokes from before it are what remains.
    if (finished.length < 2) commit(before.current)
  }

  return (
    <FieldShell path={path} field={field} label={label}>
      <div data-formancy-part="signature">
        <svg
          ref={surface}
          data-formancy-part="signature-surface"
          style={preventsScroll}
          viewBox={`0 0 ${String(width)} ${String(height)}`}
          // A graphic with a name, not a control: the things that take input are
          // the box and the button beside it, and claiming otherwise would put a
          // control in the tab order that a keyboard cannot use.
          role="img"
          aria-label={label}
          onPointerDown={onPointerDown}
          onPointerMove={onPointerMove}
          onPointerUp={onPointerUp}
          onPointerLeave={onPointerUp}
        >
          {drawn.map((points, at) => (
            <path
              // Index: strokes are appended and never reordered, and a stroke has
              // no identity of its own to key by.
              key={at}
              data-formancy-part="signature-stroke"
              d={points.map(([x, y], step) => `${step === 0 ? 'M' : 'L'}${String(x)} ${String(y)}`).join(' ')}
              fill="none"
            />
          ))}
        </svg>

        <input
          data-formancy-part="signature-typed"
          type="text"
          value={answer.typed ?? ''}
          aria-label="Type your name"
          onChange={(event) => {
            const typed = event.target.value
            field.setValue(typed === '' ? null : { typed })
          }}
          onBlur={field.touch}
        />

        <button
          data-formancy-part="signature-clear"
          type="button"
          onClick={() => {
            stroke.current = null
            before.current = []
            field.setValue(null)
          }}
        >
          Clear
        </button>
      </div>
    </FieldShell>
  )
}
