// packages/angular/src/fields/typeahead-field.ts
import { ChangeDetectionStrategy, Component, computed, input, signal } from '@angular/core'
import { narrowOptionsByLabel } from '@formancy/spec'
import { injectField } from '../field.js'
import { injectFormText } from '../text.js'
import { FieldComponentBase, FormancyFieldShell } from './field-shell.js'


/**
 * A combobox over the same answer a select holds.
 *
 * One file per control, because a control changes for its own reasons.
 * These were one 1,909-line file — the second largest in the repository,
 * and the place things went.
 */
/**
 * `widget: "typeahead"` - the same select, narrowed by typing.
 *
 * An ARIA 1.2 editable combobox over a listbox popup: a text box with
 * `role="combobox"` and a `<ul role="listbox">` of `<li role="option">`. DOM focus
 * never leaves the text box, so the arrowed-over option is named by
 * `aria-activedescendant` - the only thing that says where somebody is when what
 * they are moving through does not hold focus.
 *
 * **The list element exists while the popup is collapsed.** `aria-expanded` and
 * `aria-controls` are required properties of the role, and an `aria-controls`
 * pointing at an element that is not there is an unresolvable IDREF - so the
 * listbox is rendered and `hidden` rather than created when it opens.
 *
 * `aria-autocomplete="list"`, never `"both"`: nothing is written into the box on
 * the person's behalf, and `"both"` announces an inline completion that does not
 * exist. No `aria-haspopup`: `listbox` is the role's implicit popup.
 *
 * While a source is being asked, the box carries `aria-busy` and is never disabled:
 * disabling the element somebody just typed into blurs it, and the browser then
 * resets focus to the document body — the same reason the scanner's button stays
 * enabled while a scan is in flight.
 *
 * `aria-selected` is on the CHOSEN option and nothing else. Following the arrow
 * keys with it tells a screen reader the answer changed every time somebody
 * pressed Down to read the next row.
 *
 * **It cannot store what somebody typed.** `setValue` is reached from two places
 * here, with an option's own value or with `null`, and the text goes nowhere but
 * the filter - which is what makes
 * [0065](../../../docs/decisions/0065-a-widget-is-authored-not-registered.md)
 * structural rather than remembered. The filter itself is
 * `narrowOptionsByLabel` from `@formancy/spec`, the same function React calls, so
 * a query cannot narrow one way here and another way there.
 *
 * Every piece of state is a signal, and the field's own state arrives through
 * `injectField`, which is a signal fed by `engine.subscribeField`. Reading
 * `engine.getFieldSnapshot` instead - or wrapping a plain call in `computed()`,
 * which has no reactive dependency at all - renders this once and never again.
 * That bug has been written twice in this repository.
 */
@Component({
  selector: 'formancy-typeahead-select',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormancyFieldShell],
  template: `
    <formancy-field-shell [field]="field" [label]="context.label" [path]="context.path">
      <!-- The popup's containing block, and the reason it is an element rather than
           nothing at all.

           The popup was absolutely positioned with 'top: auto', on the reasoning that
           it would then land at its STATIC position -- where it would have sat in the
           flow, directly under the box. That holds inside a block container and NOT
           inside a grid or flex one, and every theme lays a field out with
           'display: grid'. For an absolutely positioned child of a grid container the
           static position is the container's own content-box origin, so the list opened
           over its own label and box rather than under them. Measured in the playground
           before the fix: the field's top edge was 457px, an in-flow child would have
           sat at 537px, and the popup sat at 459px.

           So the popup is given a containing block that wraps the control and nothing
           else, and every theme positions it against that explicitly. The status region
           stays OUTSIDE it, because it is a row of the field's grid exactly as the
           error region is. The React binding does the same, for the same reason. -->
      <div data-formancy-part="typeahead-anchor">
        <input
          type="text"
          role="combobox"
          [id]="control().id"
          [attr.name]="control().name"
          [attr.aria-invalid]="control()['aria-invalid']"
          [attr.aria-required]="control()['aria-required']"
          [attr.aria-describedby]="control()['aria-describedby']"
          [disabled]="control().disabled === true"
          data-formancy-part="typeahead"
          autocomplete="off"
          aria-autocomplete="list"
          [attr.aria-busy]="remote.busy() ? 'true' : null"
          [attr.aria-expanded]="expanded()"
          [attr.aria-controls]="listboxId()"
          [attr.aria-activedescendant]="activeId()"
          [value]="text()"
          (input)="onInput($event)"
          (click)="open.set(true)"
          (keydown)="onKeyDown($event)"
          (blur)="onBlur()"
        />
        <!-- Named, because the listbox role is one whose accessible name is required.
             Not with the name the field already has: two elements answering to the
             same accessible name make every query by that name ambiguous. -->
        <ul
          [id]="listboxId()"
          role="listbox"
          [attr.aria-label]="popupLabel()"
          data-formancy-part="typeahead-listbox"
          [hidden]="!expanded()"
        >
          @for (option of matches(); track option.value) {
            <li [id]="optionId(option.value)" role="option" data-formancy-part="typeahead-option" [attr.data-active]="option.value === activeValue() ? 'true' : null" [attr.aria-selected]="chosen()?.value === option.value ? 'true' : null" (mousedown)="$event.preventDefault()" (click)="choose(option.value)">{{ option.label }}</li>
          }
        </ul>
      </div>
      <!-- Present from the start and empty until there is something to say: a live
           region created at the moment it gets its text is one several screen
           readers never announce. -->
      <!-- ONE region, four things it may say, and never the error region: a source
           being down is not a wrong answer, and the error region is the control's
           describedby target carrying the engine's verdict. -->
      <p role="status" data-formancy-part="typeahead-status" [attr.data-state]="statusState()">{{ statusMessage() }}</p>
    </formancy-field-shell>
  `,
})
export class FormancyTypeaheadSelect extends FieldComponentBase {
  /**
   * What is in the box while somebody types, or null when the box is simply
   * showing the answer.
   *
   * Two states rather than one string, because "empty because they cleared it" and
   * "empty because there is no answer" are different facts, and only the first
   * clears the answer on the way out.
   */
  protected readonly query = signal<string | null>(null)
  protected readonly open = signal(false)
  /** The arrowed-over option by VALUE, not by index: the filtered list changes on
   *  every keystroke and an index would point at a different row after one. */
  protected readonly activeValue = signal<string | null>(null)

  /**
   * The option the form currently holds, looked up in what is OFFERED.
   *
   * `options()` is the document's list alone, and a field with `optionsSource` has
   * none — the schema forbids both — so looking there made `chosen` permanently
   * undefined for a sourced field, and the box showed an empty string over a stored
   * answer. React looked it up in the offered list from the start; this is the
   * divergence that made them two different controls.
   */
  protected readonly chosen = computed(() => {
    const value = this.field.snapshot().value
    return this.offered().find((option) => option.value === value)
  })

  /**
   * A source is the AUTHORITY on what matches: it was handed the query, and
   * re-folding its rows here would drop ones it matched on data the person cannot
   * see. A host wanting fetch-once-filter-locally composes `narrowOptionsByLabel` in
   * its own resolver, which is why that function lives in `@formancy/spec`.
   */
  protected readonly matches = computed(() =>
    this.remote.sourced()
      ? this.offered()
      : narrowOptionsByLabel(this.options(), this.query() ?? ''),
  )

  /** Collapsed whenever there is nothing on the screen, so `aria-expanded` never
   *  claims a popup a person cannot see. */
  protected readonly expanded = computed(() => this.open() && this.matches().length > 0)

  protected readonly text = computed(() => this.query() ?? this.chosen()?.label ?? '')

  protected readonly listboxId = computed(() => `${this.control().id}:listbox`)

  private readonly words = injectFormText()

  protected readonly popupLabel = computed(() =>
    this.words('options.suggestions', { label: this.context.label }),
  )

  private readonly activeIndex = computed(() =>
    this.matches().findIndex((option) => option.value === this.activeValue()),
  )

  /** Absent rather than empty when nothing is active: an empty IDREF is a broken
   *  reference, not a way of saying "nothing". Angular omits an attribute bound to
   *  null, which is exactly that. */
  protected readonly activeId = computed(() => {
    const index = this.activeIndex()
    if (!this.expanded() || index === -1) return null
    return this.optionId(this.matches()[index]!.value)
  })

  /**
   * A source's own words win over "no options match": while a request is in flight,
   * "nothing matched" is not yet true.
   */
  protected readonly statusMessage = computed(() => {
    const fromSource = this.remote.status()
    if (fromSource !== '') return fromSource
    return this.open() && this.matches().length === 0 && !this.remote.busy()
      ? this.words('options.noMatch')
      : ''
  })

  /** What the region is saying, as a word a theme can select on. */
  protected readonly statusState = computed(() => {
    if (this.remote.busy()) return 'busy'
    if (this.remote.failed()) return 'failed'
    if (this.remote.status() !== '') return 'hint'
    return this.open() && this.matches().length === 0 ? 'empty' : null
  })

  /** One option's element id, in the shape the radio group already uses. */
  protected optionId(value: string): string {
    return `${this.control().id}:option:${value}`
  }

  /**
   * The one place the query changes, because it is two facts that must never disagree:
   * what the box shows, and what the source is asked for.
   *
   * They were separate signals and only typing wrote the second, so after choosing a
   * row or leaving the field the source kept answering the abandoned query while the
   * box showed the answer — and the popup on the next click held rows for a word
   * nobody had typed. React derives both from one piece of state, which is why it
   * never had this.
   */
  private setQuery(next: string | null): void {
    this.query.set(next)
    this.sourceQuery.set(next ?? '')
  }

  protected onInput(event: Event): void {
    this.setQuery((event.target as HTMLInputElement).value)
    this.open.set(true)
    // Nothing is active on a keystroke: aria-activedescendant is ABSENT rather
    // than pointing at a row the person has not moved to.
    this.activeValue.set(null)
  }

  protected onKeyDown(event: KeyboardEvent): void {
    const matches = this.matches()

    if (event.key === 'ArrowDown' || event.key === 'ArrowUp') {
      event.preventDefault()
      if (!this.open()) {
        this.open.set(true)
        // Opens ON the answer when there is one, so Down then Enter cannot
        // quietly change an answer somebody only wanted to look at.
        const fallback = event.key === 'ArrowDown' ? matches[0] : matches[matches.length - 1]
        this.activeValue.set(this.chosen()?.value ?? fallback?.value ?? null)
        return
      }
      this.moveActive(event.key === 'ArrowDown' ? 1 : -1)
      return
    }

    if ((event.key === 'Home' || event.key === 'End') && this.expanded()) {
      // The popup's keys while it is open. Left to the caret, a long list is
      // reachable only by holding Down.
      event.preventDefault()
      this.activeValue.set(
        (event.key === 'Home' ? matches[0]! : matches[matches.length - 1]!).value,
      )
      return
    }

    if (event.key === 'Enter') {
      // Only while the list is showing. Otherwise Enter belongs to the form, and a
      // control that swallowed it would break submitting from the keyboard.
      if (!this.expanded()) return
      event.preventDefault()
      const index = this.activeIndex()
      if (index === -1) {
        this.open.set(false)
        return
      }
      this.choose(matches[index]!.value)
      return
    }

    if (event.key === 'Escape') {
      if (!this.open() && this.query() === null) return
      event.preventDefault()
      // "Never mind about this list", not "delete what I chose earlier": the query
      // is abandoned and the ANSWER is untouched.
      this.open.set(false)
      this.activeValue.set(null)
      this.setQuery(null)
    }
  }

  protected choose(value: string): void {
    this.field.setValue(value)
    this.setQuery(null)
    this.open.set(false)
    this.activeValue.set(null)
  }

  protected onBlur(): void {
    this.open.set(false)
    this.activeValue.set(null)
    const typed = this.query()
    if (typed !== null) {
      // An emptied box is the empty option, and the only route to null. Anything
      // else typed is abandoned - it was never an answer.
      if (typed.trim() === '') this.field.setValue(null)
      this.setQuery(null)
    }
    this.field.touch()
  }

  private moveActive(delta: number): void {
    const matches = this.matches()
    if (matches.length === 0) return
    const index = this.activeIndex()
    const from = index === -1 ? (delta > 0 ? -1 : matches.length) : index
    // Clamped, not wrapped: Down means further down the list, and a list that
    // jumps back to the top moves somebody past the end without saying so.
    const next = Math.min(Math.max(from + delta, 0), matches.length - 1)
    this.activeValue.set(matches[next]!.value)
  }
}

// packages/react/src/fields/typeahead-field.tsx
import { useState } from 'react'
import type { KeyboardEvent } from 'react'
import { narrowOptionsByLabel } from '@formancy/spec'
import { useFormText } from '../context.js'
import type { FieldBinding } from '../use-field.js'
import { useSourcedOptions } from '../use-sourced-options.js'
import { FieldShell, optionDomId, statusState } from './internals.js'
import type { FieldComponentProps } from './internals.js'


/**
 * A combobox over the same answer a select holds.
 *
 * One file per control, because a control changes for its own reasons.
 * These were one 2,154-line file — the largest in the repository.
 */
export function TypeaheadSelectField({
  path,
  label,
  field,
}: FieldComponentProps & {
  field: FieldBinding
}) {
  const text = useFormText()
  /**
   * What is in the box while somebody types, or null when the box is simply
   * showing the answer.
   *
   * Two states rather than one string, because "empty because they cleared it"
   * and "empty because there is no answer" are different facts, and only the
   * first clears the answer on the way out.
   */
  const [query, setQuery] = useState<string | null>(null)
  const [open, setOpen] = useState(false)
  /** The arrowed-over option by VALUE, not by index: the filtered list changes on
   *  every keystroke and an index would point at a different row after one. */
  const [activeValue, setActiveValue] = useState<string | null>(null)

  // The options, from the document or from the deployment. The query goes in so a
  // source is asked what somebody is looking for rather than for everything.
  const sourced = useSourcedOptions({ ...field, path }, query ?? '')
  const options = sourced.options

  const chosen = options.find((option) => option.value === field.value)
  // A source is the authority on what matches: it was handed the query, and
  // re-folding its rows here would drop ones it matched on data the person cannot
  // see. A host that wants fetch-once-filter-locally composes `narrowOptionsByLabel`
  // in its own resolver, which is why that function lives in `@formancy/spec`.
  const matches =
    sourced.remote === null ? narrowOptionsByLabel(options, query ?? '') : options
  /** Collapsed whenever there is nothing on the screen, so `aria-expanded` never
   *  claims a popup a person cannot see. */
  const expanded = open && matches.length > 0
  const activeIndex = matches.findIndex((option) => option.value === activeValue)
  const activeId =
    expanded && activeIndex !== -1 ? optionDomId(field, matches[activeIndex]!.value) : undefined
  const listboxId = `${field.ids.control}:listbox`

  const choose = (value: string): void => {
    field.setValue(value)
    setQuery(null)
    setOpen(false)
    setActiveValue(null)
  }

  const moveActive = (delta: number): void => {
    if (matches.length === 0) return
    const from = activeIndex === -1 ? (delta > 0 ? -1 : matches.length) : activeIndex
    // Clamped, not wrapped: Down means further down the list, and a list that
    // jumps back to the top moves somebody past the end without saying so.
    const next = Math.min(Math.max(from + delta, 0), matches.length - 1)
    setActiveValue(matches[next]!.value)
  }

  const onKeyDown = (event: KeyboardEvent<HTMLInputElement>): void => {
    if (event.key === 'ArrowDown' || event.key === 'ArrowUp') {
      event.preventDefault()
      if (!open) {
        setOpen(true)
        // Opens ON the answer when there is one, so Down then Enter cannot
        // quietly change an answer somebody only wanted to look at.
        const fallback = event.key === 'ArrowDown' ? matches[0] : matches[matches.length - 1]
        setActiveValue(chosen?.value ?? fallback?.value ?? null)
        return
      }
      moveActive(event.key === 'ArrowDown' ? 1 : -1)
      return
    }
    if ((event.key === 'Home' || event.key === 'End') && expanded) {
      // The popup's keys while it is open. Left to the caret, a long list is
      // reachable only by holding Down.
      event.preventDefault()
      setActiveValue((event.key === 'Home' ? matches[0]! : matches[matches.length - 1]!).value)
      return
    }
    if (event.key === 'Enter') {
      // Only while the list is showing. Otherwise Enter belongs to the form, and
      // a control that swallowed it would break submitting from the keyboard.
      if (!expanded) return
      event.preventDefault()
      if (activeIndex === -1) {
        setOpen(false)
        return
      }
      choose(matches[activeIndex]!.value)
      return
    }
    if (event.key === 'Escape') {
      if (!open && query === null) return
      event.preventDefault()
      // "Never mind about this list", not "delete what I chose earlier": the
      // query is abandoned and the ANSWER is untouched.
      setOpen(false)
      setActiveValue(null)
      setQuery(null)
    }
  }

  const onBlur = (): void => {
    setOpen(false)
    setActiveValue(null)
    if (query !== null) {
      // An emptied box is the empty option, and the only route to null. Anything
      // else typed is abandoned - it was never an answer.
      if (query.trim() === '') field.setValue(null)
      setQuery(null)
    }
    field.touch()
  }

  return (
    <FieldShell path={path} field={field} label={label}>
      {/* The popup's containing block, and the reason it is an element rather than
          nothing at all.

          The popup was absolutely positioned with `top: auto`, on the reasoning that it
          would then land at its STATIC position -- where it would have sat in the flow,
          directly under the box. That holds inside a block container and NOT inside a
          grid or flex one, and every theme lays a field out with `display: grid`. For an
          absolutely positioned child of a grid container the static position is the
          container's own content-box origin, so the list opened over its own label and
          box rather than under them. Measured in the playground before the fix: the
          field's top edge was 457px, an in-flow child would have sat at 537px, and the
          popup sat at 459px.

          So the popup is given a containing block that wraps the control and nothing
          else, and every theme positions it against that explicitly. The status region
          stays OUTSIDE it, because it is a row of the field's grid exactly as the error
          region is. */}
      <div data-formancy-part="typeahead-anchor">
        <input
          type="text"
          role="combobox"
          {...field.controlProps}
          data-formancy-part="typeahead"
          // The browser's own suggestion list would sit over this one. This is not
          // the HTML autofill token WCAG 1.3.5 asks for: that is a separate thing
          // the spec has deliberately not spent the word on yet.
          autoComplete="off"
          aria-expanded={expanded}
          aria-controls={listboxId}
          aria-autocomplete="list"
          {...(sourced.remote?.busy === true
            ? // Busy, never disabled: disabling the element somebody just typed into
              // blurs it and the browser resets focus to the document body -- the same
              // reason the scanner's button stays enabled while a scan is in flight.
              { 'aria-busy': true }
            : {})}
          {...(activeId === undefined ? {} : { 'aria-activedescendant': activeId })}
          value={query ?? chosen?.label ?? ''}
          onChange={(event) => {
            setQuery(event.target.value)
            setOpen(true)
            // Nothing is active on a keystroke: aria-activedescendant is ABSENT
            // rather than pointing at a row the person has not moved to.
            setActiveValue(null)
          }}
          onClick={() => setOpen(true)}
          onKeyDown={onKeyDown}
          onBlur={onBlur}
        />
        {/* Named, because `listbox` is one of the roles whose accessible name is
            required -- `aria-query`'s `listboxRole.accessibleNameRequired` is true.
            axe in jsdom does NOT report its absence, measured by removing this line
            and watching the audit below stay green, so the case that holds it in
            place is a query by role AND name rather than the auditor.

            Not the field's own name: two elements answering to the same accessible
            name make "the control called X" ambiguous for every query that uses it,
            starting with the conformance driver's own. */}
        <ul
          id={listboxId}
          role="listbox"
          aria-label={text('options.suggestions', { label })}
          data-formancy-part="typeahead-listbox"
          hidden={!expanded}
        >
          {matches.map((option) => (
            <li
              key={option.value}
              id={optionDomId(field, option.value)}
              role="option"
              data-formancy-part="typeahead-option"
              data-active={option.value === activeValue ? 'true' : undefined}
              {...(chosen?.value === option.value ? { 'aria-selected': true } : {})}
              // Keeps DOM focus in the text box, which is the pattern's whole
              // premise; without it the blur handler runs before the click and the
              // click lands on a list that has already gone.
              onMouseDown={(event) => event.preventDefault()}
              onClick={() => choose(option.value)}
            >
              {option.label}
            </li>
          ))}
        </ul>
      </div>
      {/* Present from the start and empty until there is something to say: a live
          region created at the moment it gets its text is one several screen
          readers never announce.

          ONE region, and never the error region. A source being down is not a wrong
          answer, and the error region is the control's `aria-describedby` target
          carrying the engine's verdict — the same line the scanner draws.

          A source's own words win over "no options match": while a request is in
          flight, "nothing matched" is not yet true. */}
      <p
        role="status"
        data-formancy-part="typeahead-status"
        {...(statusState({ sourced, open, matches: matches.length }) === undefined
          ? {}
          : { 'data-state': statusState({ sourced, open, matches: matches.length }) })}
      >
        {sourced.remote !== null && sourced.remote.status !== ''
          ? sourced.remote.status
          : open && matches.length === 0 && sourced.remote?.busy !== true
            ? text('options.noMatch')
            : ''}
      </p>
    </FieldShell>
  )
}
