// packages/builder-react/src/scenario-pane.tsx
import { useEffect, useMemo, useState, useSyncExternalStore } from 'react'
import type { ReactElement } from 'react'
import { comparedToLastRun, createRunHistory, scenarioStatus } from '@formancy/builder-core'
import { runScenarios } from '@formancy/core'
import type { AskModel, BuilderSession, DraftRun } from '@formancy/builder-core'
import type { Scenario } from '@formancy/core'
import { ScenarioDrafts } from './scenario-drafts.js'

/**
 * What this form is supposed to do, run against what it does now.
 *
 * A condition type-checks and is still the wrong business rule:
 * `leaveType == 'other'` and `leaveType != 'other'` both compile, both satisfy
 * every gate this product has, and one of them asks a question nobody should
 * be asked. Nothing that reads the document can tell them apart, because the
 * difference is between the document and what somebody meant
 * ([0110](../../../docs/decisions/0110-a-form-is-checked-against-examples.md)).
 *
 * So this pane runs examples with their answers written down, after every
 * edit, and says **which ones stopped holding**. Not how many fail: a standing
 * total is a number somebody reads once. What was holding before you touched
 * this and is not now is the sentence that gets acted on, and the repairs are
 * reported beside it so a panel is not only ever bad news.
 *
 * **The scenarios are the host's.** They arrive as a prop and changes go back
 * out through `onChange`, exactly as `ask` and the uploader do: this package
 * decides nothing about where they are kept, and a host putting them in a
 * `.scenarios.json` beside the form gets a CI gate out of the same file. With
 * none given the pane renders nothing rather than an empty table.
 *
 * **Given a model as well, it drafts them.** With `ask` and `onChange` both given, the
 * pane draws `ScenarioDrafts` beneath the list: the author says what the form should do,
 * a model drafts examples from that and the form's fields — never its rules — and each one
 * is kept or discarded by the person, with the verdict the list will give it
 * ([0162](../../../docs/decisions/0162-an-example-is-drafted-from-what-the-author-said.md)).
 * Given `drafting` as well, from `createDraftRun`, the drafting is the host's: it outlives
 * the pane, and the pane drawn next over the same form shows it
 * ([0164](../../../docs/decisions/0164-a-translation-is-held-for-its-language-and-a-draft-for-its-form.md)).
 *
 * `useSyncExternalStore` against the session's revision, which is this
 * repository's ordinary way of reading a store — not a `useEffect` copying
 * state into state.
 */

export interface ScenarioPaneProps {
  session: BuilderSession
  /** Held by the host. Absent means the feature is not configured. */
  scenarios?: readonly Scenario[] | undefined
  /** Called when somebody removes one. Absent makes the list read-only. */
  onChange?: ((next: readonly Scenario[]) => void) | undefined
  /**
   * Where every scenario starts — the templates' `sample`, by another name.
   *
   * Not optional in practice for any real form: a document with required
   * fields is invalid before a scenario has set anything, so every scenario
   * would report the same six `required` errors and none of them would be
   * about what the scenario is for. Found by pointing this pane at the
   * playground's own starter.
   */
  initialValue?: Readonly<Record<string, unknown>> | undefined
  /**
   * `client` by default. `server` is what the publish gate and the submission
   * endpoint run, and a form that behaves differently in the two is the drift
   * this product exists to prevent — so it is worth being able to ask.
   */
  mode?: 'client' | 'server'
  /**
   * A model to draft examples with, as `PromptPane` takes it. Drafting is drawn only when
   * `onChange` is given too: a draft somebody keeps has to go somewhere.
   */
  ask?: AskModel | undefined
  /** How many times drafting asks the model. Three by default. */
  attempts?: number
  /**
   * The drafting run, held by the host, from `createDraftRun`: it outlives this pane, and a
   * pane drawn over the same form later shows its drafts. Absent, the drafting part holds its
   * own, and ends it when it goes or is handed another session (0157, 0162).
   */
  drafting?: DraftRun | undefined
}

export function ScenarioPane({
  session,
  scenarios,
  onChange,
  initialValue,
  mode,
  ask,
  attempts,
  drafting,
}: ScenarioPaneProps): ReactElement | null {
  const revision = useSyncExternalStore(
    (listener) => session.subscribe(listener),
    () => session.revision(),
  )

  const results = useMemo(
    () =>
      scenarios === undefined
        ? []
        : runScenarios(session.document(), scenarios, {
            ...(initialValue === undefined ? {} : { initialValue }),
            ...(mode === undefined ? {} : { mode }),
          }),
    // `revision` is the dependency that means "the document changed". Reading
    // it here rather than the document itself is what makes the rerun happen
    // on an edit and not on every render.
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [session, scenarios, initialValue, mode, revision],
  )

  /*
   * The previous run, and the session it was over, held by one history for the pane's
   * life rather than in state.
   *
   * It is not rendered on its own and setting it would schedule a second
   * render after every edit, which is a re-render per keystroke on a panel
   * sitting beside a form somebody is typing into. A run over another session is
   * compared with nothing: that is another document, not an edit of this one.
   */
  const [history] = useState(createRunHistory)
  const [change, setChange] = useState(() => comparedToLastRun(undefined, []))
  useEffect(() => {
    setChange(history.compare(session, results))
  }, [history, session, results])

  if (scenarios === undefined) return null

  const failing = results.filter((result) => !result.passed)

  return (
    <section data-formancy-part="scenario-pane" aria-label={session.text('scenarios.label')}>
      {/* One polite region. A regression that only appears visually is one a
          screen-reader user learns about by submitting a broken form. */}
      <p role="status" data-formancy-part="scenario-status">
        {scenarioStatus(results.length, failing.length, change, session.text)}
      </p>

      {results.length === 0 ? (
        <p data-formancy-part="scenario-empty">{session.text('scenarios.empty')}</p>
      ) : (
        <ul data-formancy-part="scenario-list">
          {results.map((result) => (
            <li
              key={result.name}
              data-passed={result.passed}
              data-regressed={change.regressions.includes(result.name)}
            >
              <strong>{result.name}</strong>
              {result.failures.length === 0 ? null : (
                <ul>
                  {result.failures.map((failure, index) => (
                    // What was expected and what happened. "Failed" sends
                    // somebody back to the document to work out which rule.
                    <li key={index} data-about={failure.about}>
                      {failure.detail}
                    </li>
                  ))}
                </ul>
              )}
              {onChange === undefined ? null : (
                <button
                  type="button"
                  onClick={() => onChange(scenarios.filter((one) => one.name !== result.name))}
                >
                  {session.text('scenarios.remove', { name: result.name })}
                </button>
              )}
            </li>
          ))}
        </ul>
      )}

      {ask === undefined || onChange === undefined ? null : (
        <ScenarioDrafts
          session={session}
          scenarios={scenarios}
          onChange={onChange}
          ask={ask}
          initialValue={initialValue}
          {...(mode === undefined ? {} : { mode })}
          {...(attempts === undefined ? {} : { attempts })}
          drafting={drafting}
        />
      )}
    </section>
  )
}

// packages/builder-angular/src/scenario-pane.ts
import { ChangeDetectionStrategy, Component, computed, input, output, signal } from '@angular/core'
import { createRunHistory, scenarioStatus } from '@formancy/builder-core'
import { BuilderTextPipe } from './text.pipe.js'
import { runScenarios } from '@formancy/core'
import { FormancyScenarioDrafts } from './scenario-drafts.js'
import type { AskModel, BuilderSession, DraftRun, Scenario, ScenarioResult } from './types.js'
import { injectBuilderView } from './view.js'

/**
 * What this form is supposed to do, run against what it does now.
 *
 * The Angular half of the React pane, and the same two things it adds over the
 * runner: it reruns when the document changes, and it names **what stopped
 * holding** rather than how many fail. A standing total is a number somebody
 * reads once; what was holding before you touched this and is not now is the
 * sentence that gets acted on
 * ([0110](../../../docs/decisions/0110-a-form-is-checked-against-examples.md)).
 *
 * What counts as a regression is `comparedToLastRun` in
 * `@formancy/builder-core`, and what it is compared with is `createRunHistory`
 * there, so the two builders cannot tell two people different things about one edit
 * ([0091](../../../docs/decisions/0091-a-second-builder-is-a-binding.md)).
 *
 * **The scenarios are the host's**, arriving as an input and leaving through
 * an output, exactly as the prompt pane's model does. With none given the pane
 * renders nothing rather than an empty table.
 *
 * **Given a model as well, it drafts them.** With `[ask]` bound and `removable` set, the
 * pane draws `formancy-scenario-drafts` beneath the list, whose kept drafts leave through
 * the same output
 * ([0162](../../../docs/decisions/0162-an-example-is-drafted-from-what-the-author-said.md)).
 * Bound to `[drafting]` as well, from `createDraftRun`, the drafting is the host's: it
 * outlives the pane, and the pane drawn next over the same form shows it
 * ([0164](../../../docs/decisions/0164-a-translation-is-held-for-its-language-and-a-draft-for-its-form.md)).
 *
 * Signals and `OnPush`, zoneless. The rerun is a `computed` over the session's
 * revision — the same subscription every other pane here uses — and the
 * previous run is held in a plain field, the history, because it is read to
 * compare and never rendered on its own.
 */
@Component({
  selector: 'formancy-scenario-pane',
  imports: [BuilderTextPipe, FormancyScenarioDrafts],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (scenarios() !== undefined) {
      <section
        data-formancy-part="scenario-pane"
        [attr.aria-label]="'scenarios.label' | builderText: text()"
      >
        <!-- One polite region. A regression that only appears visually is one a
             screen-reader user learns about by submitting a broken form. -->
        <p role="status" data-formancy-part="scenario-status">{{ status() }}</p>

        @if (results().length === 0) {
          <p data-formancy-part="scenario-empty">{{ 'scenarios.empty' | builderText: text() }}</p>
        } @else {
          <ul data-formancy-part="scenario-list">
            @for (result of results(); track result.name) {
              <li
                [attr.data-passed]="result.passed"
                [attr.data-regressed]="change().regressions.includes(result.name)"
              >
                <strong>{{ result.name }}</strong>
                @if (result.failures.length > 0) {
                  <ul>
                    @for (failure of result.failures; track $index) {
                      <!-- What was expected and what happened. "Failed" sends
                           somebody back to the document to find the rule. -->
                      <li [attr.data-about]="failure.about">{{ failure.detail }}</li>
                    }
                  </ul>
                }
                @if (removable()) {
                  <button type="button" (click)="remove(result.name)">
                    {{ 'scenarios.remove' | builderText: text() : { name: result.name } }}
                  </button>
                }
              </li>
            }
          </ul>
        }

        <!-- A draft kept goes where a Remove does: out through the one output, so it is
             drawn only where somebody is listening to it. -->
        @if (ask(); as model) {
          @if (removable()) {
            <formancy-scenario-drafts
              [session]="session()"
              [scenarios]="scenarios()!"
              [ask]="model"
              [initialValue]="initialValue()"
              [mode]="mode()"
              [attempts]="attempts()"
              [drafting]="drafting()"
              (scenariosChange)="scenariosChange.emit($event)"
            />
          }
        }
      </section>
    }
  `,
})
export class FormancyScenarioPane {
  readonly session = input.required<BuilderSession>()
  /** Held by the host. Absent means the feature is not configured. */
  readonly scenarios = input<readonly Scenario[] | undefined>(undefined)
  /**
   * Where every scenario starts — the templates' `sample`, by another name.
   *
   * Not optional in practice for any real form: a document with required
   * fields is invalid before a scenario has set anything, so every scenario
   * would report the same `required` errors and none would be about what the
   * scenario is for.
   */
  readonly initialValue = input<Readonly<Record<string, unknown>> | undefined>(undefined)
  /**
   * `client` by default. `server` is what the publish gate and the submission
   * endpoint run, and a form that behaves differently in the two is the drift
   * this product exists to prevent.
   */
  readonly mode = input<'client' | 'server' | undefined>(undefined)
  /** Emitted when somebody removes one. Unsubscribed makes the list read-only. */
  readonly scenariosChange = output<readonly Scenario[]>()
  /**
   * Whether the remove buttons are drawn.
   *
   * An input rather than "is anybody listening to the output", which Angular
   * does not answer: a button whose event goes nowhere is worse than no
   * button, and guessing at a subscription would be guessing.
   */
  readonly removable = input(false)
  /**
   * A model to draft examples with, as the prompt pane takes it. Drafting is drawn only when
   * `removable` is set too: a draft somebody keeps leaves through `scenariosChange`, and the
   * pane draws buttons for that output only when the host says it listens.
   */
  readonly ask = input<AskModel | undefined>(undefined)
  /** How many times drafting asks the model. Three by default. */
  readonly attempts = input<number | undefined>(undefined)
  /**
   * The drafting run, held by the host, from `createDraftRun`: it outlives this pane, and a
   * pane drawn over the same form later shows its drafts. Unbound, the drafting part holds
   * its own, and ends it when it is destroyed or handed another session (0157, 0162).
   */
  readonly drafting = input<DraftRun | undefined>(undefined)

  private readonly view = injectBuilderView(this.session)
  /** The previous run and its session; a run over another session is compared with nothing. */
  private readonly history = createRunHistory()

  protected readonly results = computed<readonly ScenarioResult[]>(() => {
    const scenarios = this.scenarios()
    if (scenarios === undefined) return []
    // Read for the dependency: the view changes identity when the document
    // does, which is what makes this rerun on an edit and not on a render.
    this.view()
    const mode = this.mode()
    const initialValue = this.initialValue()
    return runScenarios(this.session().document(), scenarios, {
      ...(initialValue === undefined ? {} : { initialValue }),
      ...(mode === undefined ? {} : { mode }),
    })
  })

  protected readonly change = computed(() => {
    const results = this.results()
    return this.history.compare(this.session(), results)
  })

  /** Every word this panel shows, in the language the session was opened in (0114). */
  protected readonly text = computed(() => this.session().text)

  /** The one sentence the live region carries — builder-core's, as the React panel's is. */
  protected readonly status = computed(() => {
    const results = this.results()
    const failing = results.filter((result) => !result.passed).length
    return scenarioStatus(results.length, failing, this.change(), this.text())
  })

  protected remove(name: string): void {
    this.scenariosChange.emit((this.scenarios() ?? []).filter((one) => one.name !== name))
  }
}
