// packages/builder-angular/src/property-panel.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
  signal,
} from '@angular/core'
import { createBuilderText, editablePropertiesFor, nameOf } from '@formancy/builder-core'
import type { BuilderText } from '@formancy/builder-core'
import type {
  BuilderSession,
  DataGridColumn,
  EditableProperty,
  FieldDef,
  FieldOption,
} from './types.js'
import { FormancyColumnsEditor } from './columns-editor.js'
import { FormancyOptionsEditor } from './options-editor.js'
import { injectBuilderView } from './view.js'

let nextId = 0

/**
 * One property's control, generated from the spec's own JSON Schema.
 *
 * Shared by the field panel and, later, the layout panel: two renderings of "a
 * property from the schema" would drift, and the drift would be invisible —
 * both panels would look fine and one would quietly stop offering a kind the
 * schema grew.
 *
 * **It keeps a draft of the text**, for the reason the options editor does. The
 * document refuses invalid states and a person typing passes through them.
 * Measured in the React panel: `span` is `anyOf: [integer, const "all"]`, so
 * typing "all" offers "a", then "al", then "all" — the first two are refused,
 * the document does not change, and a box bound straight to it re-renders empty,
 * so the next keystroke lands in an empty box. The word could not be typed at
 * all. The box shows the draft, every edit is offered to the session, and a
 * refusal leaves the document where it was.
 */
@Component({
  selector: 'formancy-property',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormancyColumnsEditor, FormancyOptionsEditor],
  template: `
    @if (property().kind === 'options') {
      <formancy-options-editor
        [options]="asOptions(value())"
        [text]="text()"
        [pictures]="property().pictures === true"
        [list]="property().list ?? 'options'"
        (changed)="changed.emit($event.length === 0 ? undefined : $event)"
      />
    } @else if (property().kind === 'columns') {
      <!-- A datagrid's columns name this field's own children, so the editor
           needs them. Nothing else in the panel does, which is why they are
           passed rather than reached for. -->
      <formancy-columns-editor
        [columns]="asColumns(value())"
        [children]="childFields()"
        [text]="text()"
        (changed)="changed.emit($event.length === 0 ? undefined : $event)"
      />
    } @else {
      <div data-formancy-part="property">
        <label [attr.for]="id">{{ property().title }}</label>

        @switch (property().kind) {
          @case ('boolean') {
            <input
              [attr.id]="id"
              [attr.aria-describedby]="hintId()"
              type="checkbox"
              [checked]="asBoolean(value())"
              (change)="onCheck($event)"
            />
          }
          @case ('enum') {
            <select
              [attr.id]="id"
              [attr.aria-describedby]="hintId()"
              (change)="onSelect($event)"
            >
              <option value="" [selected]="asText(value()) === ''"></option>
              @for (choice of property().choices ?? []; track choice) {
                <option [value]="choice" [selected]="asText(value()) === choice">{{ choice }}</option>
              }
            </select>
          }
          @case ('strings') {
            <!-- One per line, not comma-separated: a media type has no comma in
                 it but an extension list somebody pastes from elsewhere often
                 does, and a separator that appears inside a value is one that
                 silently splits it. -->
            <textarea
              [attr.id]="id"
              [attr.aria-describedby]="hintId()"
              rows="3"
              [value]="asLines(value())"
              (input)="onLines($event)"
            ></textarea>
          }
          @default {
            <input
              [attr.id]="id"
              [attr.aria-describedby]="hintId()"
              [attr.type]="property().kind === 'number' ? 'number' : 'text'"
              [value]="draft()"
              (input)="onText($event)"
            />
          }
        }

        @if (property().description !== '') {
          <p [attr.id]="id + '-hint'" data-formancy-part="property-hint">
            {{ property().description }}
          </p>
        }
      </div>
    }
  `,
})
export class FormancyProperty {
  readonly property = input.required<EditableProperty>()
  readonly value = input<unknown>(undefined)
  /** The field's own children, which only the columns editor needs. */
  readonly childFields = input<readonly FieldDef[]>([])
  /** The session's language, for the two editors that have words of their own. */
  readonly text = input<BuilderText>(createBuilderText())
  readonly changed = output<unknown>()

  protected readonly id = `formancy-property-${String((nextId += 1))}`

  private readonly local = signal<string | null>(null)
  /** What this control last sent, so its own echo is not adopted as a change. */
  private pushed = ''

  protected readonly hintId = computed(() =>
    this.property().description === '' ? null : `${this.id}-hint`,
  )

  protected readonly draft = computed((): string => {
    const incoming = this.asText(this.value())
    const held = this.local()
    if (held !== null && incoming === this.pushed) return held
    return incoming
  })

  protected asText(raw: unknown): string {
    return typeof raw === 'string' || typeof raw === 'number' ? String(raw) : ''
  }

  protected asBoolean(raw: unknown): boolean {
    return typeof raw === 'boolean' ? raw : this.property().default === true
  }

  protected asLines(raw: unknown): string {
    return Array.isArray(raw) ? (raw as unknown[]).map(String).join('\n') : ''
  }

  protected asOptions(raw: unknown): FieldOption[] {
    return Array.isArray(raw) ? (raw as FieldOption[]) : []
  }

  protected asColumns(raw: unknown): DataGridColumn[] {
    return Array.isArray(raw) ? (raw as DataGridColumn[]) : []
  }

  protected onCheck(event: Event): void {
    this.changed.emit((event.target as HTMLInputElement).checked)
  }

  protected onSelect(event: Event): void {
    this.changed.emit((event.target as HTMLSelectElement).value)
  }

  protected onLines(event: Event): void {
    const next = (event.target as HTMLTextAreaElement).value
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line !== '')
    this.changed.emit(next.length === 0 ? undefined : next)
  }

  protected onText(event: Event): void {
    const raw = (event.target as HTMLInputElement).value
    const property = this.property()

    if (property.kind !== 'number') {
      // A property the format writes as "a number or a word" — `span` is
      // `anyOf: [integer, const "all"]` — needs the number handed over AS a
      // number. Read from the schema, never from the property's name, so the
      // next one written that way works without anybody remembering this.
      if (property.numericAlternative === true && /^-?\d+(\.\d+)?$/.test(raw)) {
        this.offer(raw, Number(raw))
        return
      }
      this.offer(raw, raw === '' ? undefined : raw)
      return
    }
    // A half-typed number is not a number. Sending NaN would fail validation on
    // every keystroke of "1e", so an unparseable box reads as cleared until it
    // parses.
    const parsed = Number(raw)
    this.offer(raw, raw === '' || Number.isNaN(parsed) ? undefined : parsed)
  }

  private offer(text: string, parsed: unknown): void {
    this.local.set(text)
    this.pushed = this.asText(parsed)
    this.changed.emit(parsed)
  }
}

/**
 * The property panel: what the schema says this field type has.
 *
 * Generated rather than written out per type. Hand-write twenty-five panels and
 * they rot within two releases; generated, a property the format grows appears
 * with its own title and description and nobody has to remember it exists.
 *
 * The definition comes from the SESSION rather than from an input. A panel handed
 * a definition captured before the edit renders controls whose value never
 * changes, so every keystroke resets the box and only the last character
 * survives — a bug any consumer would reproduce by wiring it the obvious way.
 */
@Component({
  selector: 'formancy-property-panel',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormancyProperty],
  template: `
    @if (def(); as field) {
      <div data-formancy-part="property-panel">
        <h2>{{ heading() }}</h2>
        <p data-formancy-part="property-panel-type">{{ field.type }}</p>

        @for (property of properties(); track property.name) {
          <formancy-property
            [property]="property"
            [value]="valueOf(property.name)"
            [childFields]="field.fields ?? []"
            [text]="session().text"
            (changed)="set(property.name, $event)"
          />
        }
      </div>
    }
  `,
})
export class FormancyPropertyPanel {
  readonly session = input.required<BuilderSession>()
  /** The field being edited. Its definition is read from the live document. */
  readonly keyPath = input.required<readonly string[]>()

  protected readonly view = injectBuilderView(this.session)

  protected readonly def = computed((): FieldDef | undefined => {
    const path = this.keyPath()
    return this.view().nodes.find(
      (candidate) =>
        candidate.keyPath.length === path.length &&
        candidate.keyPath.every((key, at) => key === path[at]),
    )?.def
  })
  protected readonly heading = computed(() => {
    const field = this.def()
    return field === undefined ? '' : nameOf(this.view().document, field)
  })
  protected readonly properties = computed((): EditableProperty[] => {
    const field = this.def()
    return field === undefined ? [] : editablePropertiesFor(field.type, field.widget, this.session().text)
  })

  protected valueOf(name: string): unknown {
    return (this.def() as unknown as Record<string, unknown> | undefined)?.[name]
  }

  protected set(name: string, value: unknown): void {
    // An empty box means "no value", not "the empty string". Writing '' would put
    // a property into the document the author just cleared, and `minLength: ''`
    // is not a thing the schema accepts.
    this.session().setFieldProperty(
      this.keyPath(),
      name,
      value === '' || value === undefined ? undefined : value,
    )
  }
}

// packages/builder-react/src/property-panel.tsx
import { useEffect, useId, useRef, useState } from 'react'
import type { ReactElement } from 'react'
import type { DataGridColumn, FieldDef, FieldOption } from '@formancy/spec'
import type { BuilderSession, BuilderText } from '@formancy/builder-core'
import { ColumnsEditor } from './columns-editor.js'
import { OptionsEditor } from './options-editor.js'
import { editablePropertiesFor } from '@formancy/builder-core'
import type { EditableProperty } from '@formancy/builder-core'
import { nameOf } from '@formancy/builder-core'
import { useBuilder } from './use-builder.js'

/**
 * The property panel, rendered from the spec's JSON Schema rather than written
 * out per field type. See properties.ts for why.
 *
 * Every control is a real labelled input with the schema's own description as
 * its hint, which is also what makes the panel navigable: a form builder whose
 * own forms are not accessible would be a poor advertisement.
 */

export interface PropertyPanelProps {
  session: BuilderSession
  /** The field being edited. Its definition is read from the live document. */
  keyPath: readonly string[]
}

export function PropertyPanel({ session, keyPath }: PropertyPanelProps): ReactElement | null {
  // The definition comes from the session rather than from a prop. A panel
  // handed a definition captured before the edit renders controlled inputs
  // whose value never changes, so every keystroke resets the box and only the
  // last character survives — a bug any consumer would reproduce by wiring it
  // the obvious way.
  const view = useBuilder(session)
  const node = view.nodes.find(
    (candidate) =>
      candidate.keyPath.length === keyPath.length &&
      candidate.keyPath.every((key, at) => key === keyPath[at]),
  )
  if (node === undefined) return null

  const def = node.def
  const properties = editablePropertiesFor(def.type, def.widget, session.text)
  const current = def as unknown as Record<string, unknown>

  return (
    <div data-formancy-part="property-panel">
      <h2>{nameOf(view.document, def)}</h2>
      <p data-formancy-part="property-panel-type">{def.type}</p>

      {properties.map((property) => (
        <PropertyField
          key={property.name}
          property={property}
          value={current[property.name]}
          // A datagrid's columns name this field's own children, so the editor needs
          // them. Nothing else in the panel does, which is why it is passed rather
          // than reached for.
          childFields={def.fields ?? []}
          text={session.text}
          onChange={(value) => {
            // An empty box means "no value", not "the empty string". Writing ''
            // would put a property into the document that the author just
            // cleared, and `minLength: ''` is not a thing the schema accepts.
            session.setFieldProperty(
              keyPath,
              property.name,
              value === '' || value === undefined ? undefined : value,
            )
          }}
        />
      ))}
    </div>
  )
}

/**
 * One property's control, shared by the field panel and the layout panel.
 *
 * Exported inside the package rather than copied: two renderings of "a property from
 * the schema" would drift, and the drift would be invisible — both panels would look
 * fine and one of them would quietly stop offering a kind the schema grew.
 */
export function PropertyField({
  property,
  value,
  childFields,
  text,
  onChange,
}: {
  property: EditableProperty
  value: unknown
  childFields: readonly FieldDef[]
  /** The session's language, for the two editors that have words of their own. */
  text: BuilderText
  onChange: (value: unknown) => void
}): ReactElement | null {
  const id = useId()
  const hintId = `${id}-hint`

  /*
   * A local draft of the text, for the reason the options editor keeps one: the
   * document refuses invalid states and a person typing passes through them.
   *
   * Measured, and it made two properties unsettable. `span` is `anyOf: [integer,
   * const "all"]`, so typing "all" offers "a", then "al", then "all" — the first two
   * are refused, the document does not change, and a purely controlled box re-renders
   * empty, so the next keystroke lands in an empty box. The word could not be typed at
   * all. Clearing a table's `columns` to retype it is the same shape: a table must have
   * one, so the empty moment is refused and the old number snaps back mid-edit.
   *
   * So the box shows the draft, every edit is offered to the session, and a refusal
   * simply leaves the document where it was. The form still cannot be PUBLISHED in an
   * invalid state — `canPublish` says no — but it can be typed in.
   */
  const asText = (raw: unknown): string =>
    typeof raw === 'string' || typeof raw === 'number' ? String(raw) : ''
  const [draft, setDraft] = useState(() => asText(value))
  const pushed = useRef(asText(value))

  useEffect(() => {
    const incoming = asText(value)
    // Only adopt a change that came from somewhere else — an undo, or another node
    // being selected. Adopting our own echo would undo the draft.
    if (incoming !== pushed.current) {
      pushed.current = incoming
      setDraft(incoming)
    }
  }, [value])

  const offer = (text: string, parsed: unknown): void => {
    setDraft(text)
    pushed.current = asText(parsed)
    onChange(parsed)
  }

  // Options are value/label pairs, and the generic path would render them as
  // a textarea full of JSON. They get an editor of their own.
  if (property.kind === 'options') {
    return (
      <OptionsEditor
        options={Array.isArray(value) ? (value as FieldOption[]) : []}
        text={text}
        pictures={property.pictures === true}
        onChange={(next) => onChange(next.length === 0 ? undefined : next)}
      />
    )
  }

  // A datagrid's columns are an array of objects, one of which names a sibling
  // field — the generic path would render that as JSON too.
  if (property.kind === 'columns') {
    return (
      <ColumnsEditor
        columns={Array.isArray(value) ? (value as DataGridColumn[]) : []}
        children={childFields}
        text={text}
        onChange={(next) => onChange(next.length === 0 ? undefined : next)}
      />
    )
  }

  const shared = {
    id,
    'aria-describedby': property.description === '' ? undefined : hintId,
  }

  // A list of plain strings, one per line. Not comma-separated: a media type
  // has no comma in it but an extension list somebody pastes from elsewhere
  // often does, and a separator that appears inside a value is a separator
  // that silently splits one.
  if (property.kind === 'strings') {
    const lines = Array.isArray(value) ? (value as unknown[]).map(String) : []
    return (
      <div data-formancy-part="property">
        <label htmlFor={id}>{property.title}</label>
        <textarea
          {...shared}
          rows={3}
          value={lines.join('\n')}
          onChange={(event) => {
            const next = event.target.value
              .split('\n')
              .map((line) => line.trim())
              .filter((line) => line !== '')
            onChange(next.length === 0 ? undefined : next)
          }}
        />
        {property.description === '' ? null : (
          <p id={hintId} data-formancy-part="property-hint">
            {property.description}
          </p>
        )}
      </div>
    )
  }

  return (
    <div data-formancy-part="property">
      <label htmlFor={id}>{property.title}</label>

      {property.kind === 'boolean' ? (
        <input
          {...shared}
          type="checkbox"
          checked={typeof value === 'boolean' ? value : property.default === true}
          onChange={(event) => onChange(event.target.checked)}
        />
      ) : property.kind === 'enum' ? (
        <select
          {...shared}
          value={typeof value === 'string' ? value : ''}
          onChange={(event) => onChange(event.target.value)}
        >
          <option value="" />
          {(property.choices ?? []).map((choice) => (
            <option key={choice} value={choice}>
              {choice}
            </option>
          ))}
        </select>
      ) : (
        <input
          {...shared}
          type={property.kind === 'number' ? 'number' : 'text'}
          value={draft}
          onChange={(event) => {
            const raw = event.target.value
            if (property.kind !== 'number') {
              // A property the format writes as "a number or a word" — `span` is
              // `anyOf: [integer, const "all"]` — needs the number handed over AS a
              // number. Measured: the string form is refused outright, so typing a
              // numeric span used to do nothing and say nothing.
              //
              // Read from the schema, never from the property's name, so the next one
              // written that way works without anybody remembering this.
              if (property.numericAlternative === true && /^-?\d+(\.\d+)?$/.test(raw)) {
                offer(raw, Number(raw))
                return
              }
              offer(raw, raw === '' ? undefined : raw)
              return
            }
            // A half-typed number is not a number. Sending NaN would fail
            // validation on every keystroke of "1e", so an unparseable box
            // reads as cleared until it parses.
            const parsed = Number(raw)
            offer(raw, raw === '' || Number.isNaN(parsed) ? undefined : parsed)
          }}
        />
      )}

      {property.description === '' ? null : (
        <p id={hintId} data-formancy-part="property-hint">
          {property.description}
        </p>
      )}
    </div>
  )
}
