// packages/builder-angular/src/translation-review.ts
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  EnvironmentInjector,
  computed,
  inject,
  input,
  signal,
} from '@angular/core'
import type { Injector } from '@angular/core'
import { NgComponentOutlet } from '@angular/common'
import { FormancyForm } from '@formancy/angular'
import {
  applyProposal,
  createStop,
  missingMessages,
  proposeTranslation,
  translateCatalogue,
  translationHeading,
  translationStatus,
  translationToReview,
} from '@formancy/builder-core'
import type { BuilderMessageId } from '@formancy/builder-core'
import { BuilderTextPipe } from './text.pipe.js'
import { previewInjector } from './translations-preview.js'
import type {
  AskModel,
  BuilderSession,
  FormSchema,
  Stop,
  TranslationProposal,
  TranslationResult,
} from './types.js'
import { injectBuilderView } from './view.js'

/** What each mark says, in the catalogue's words. */
const FLAGS: Readonly<Record<'stale' | 'unchanged', BuilderMessageId>> = {
  stale: 'translate.flag.stale',
  unchanged: 'translate.flag.unchanged',
}

/**
 * Asking a model for the messages a language is missing, and reviewing its answer message
 * by message before it lands — the Angular half of the React `TranslationReview`.
 *
 * A model's translation is a model's edit, and one that changes what a question asks in a
 * language the person reviewing may read less well than the source
 * ([0161](../../../docs/decisions/0161-a-model-translates-only-what-is-missing.md)). So it
 * is shown rather than applied (0109): every message it would write, its source beside
 * what was there and what is proposed, a mark on anything to look at, and the form as it
 * would read in that language. Apply is `applyProposal`, refused when the form has moved
 * since, one undo step otherwise.
 *
 * What is asked, kept, marked, held for review and said is `@formancy/builder-core`'s, so
 * the two builders cannot decide it differently (0091). Signals and `OnPush`, zoneless; the run is one
 * `await` inside a click, and `DestroyRef` stops it when the part goes — another language
 * chosen, another tab.
 */
@Component({
  selector: 'formancy-translation-review',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [BuilderTextPipe, NgComponentOutlet],
  template: `
    @if (shown()) {
      <div data-formancy-part="translate">
        @if (reviewed() === undefined) {
          <button
            type="button"
            data-formancy-part="translate-ask"
            [disabled]="busy()"
            (click)="run()"
          >
            {{
              busy()
                ? ('translate.asking' | builderText: text())
                : ('translate.ask' | builderText: text() : { count: missing() })
            }}
          </button>
        }
        @if (busy()) {
          <button type="button" (click)="stop()">{{ 'prompt.stop' | builderText: text() }}</button>
        }

        <p role="status" data-formancy-part="translate-status">{{ status() }}</p>

        <!-- Outside the review: when everything the model wrote was dropped there is no
             review, and this is what says why. -->
        @if (dropped(); as list) {
          <p data-formancy-part="translate-dropped">
            {{ 'translate.dropped' | builderText: text() : { list: text().list(list) } }}
          </p>
        }

        @if (reviewed(); as waiting) {
          <section data-formancy-part="translate-review" [attr.aria-labelledby]="reviewId">
            <h3 [id]="reviewId">{{ heading() }}</h3>
            <table data-formancy-part="translate-rows">
              <thead>
                <tr>
                  <th scope="col">{{ defaultLocale() }}</th>
                  <th scope="col">{{ 'translate.was' | builderText: text() }}</th>
                  <th scope="col">{{ 'translate.now' | builderText: text() }}</th>
                  <th scope="col">{{ 'translate.flags' | builderText: text() }}</th>
                </tr>
              </thead>
              <tbody>
                @for (row of waiting.rows; track row.id) {
                  <tr>
                    <!-- The source, not the id, as the translations table shows it. -->
                    <th scope="row">{{ row.source }}</th>
                    <td>
                      {{ row.was === '' ? ('translations.missing' | builderText: text()) : row.was }}
                    </td>
                    <!-- The model's words, as text, in the language they are written in. -->
                    <td [attr.lang]="locale()">{{ row.now }}</td>
                    <td>
                      @for (flag of row.flags; track flag) {
                        <span data-formancy-part="translate-flag">{{
                          flags[flag] | builderText: text()
                        }}</span>
                      }
                    </td>
                  </tr>
                }
              </tbody>
            </table>
            <!-- The form as it would read in this language, with its own ids beside the
                 pane's preview of the form as it is. -->
            <section
              [attr.aria-label]="'translate.preview' | builderText: text() : { locale: locale() }"
              data-formancy-part="translations-preview"
            >
              @if (previewInjector(); as injector) {
                <ng-container
                  [ngComponentOutlet]="form"
                  [ngComponentOutletInjector]="injector"
                  [ngComponentOutletInputs]="previewInputs()"
                />
              }
            </section>
            <button type="button" [disabled]="busy()" (click)="apply()">
              {{ 'translate.apply' | builderText: text() }}
            </button>
            <button type="button" [disabled]="busy()" (click)="discard()">
              {{ 'prompt.discard' | builderText: text() }}
            </button>
            @if (waiting.stillMissing.length > 0) {
              <button type="button" [disabled]="busy()" (click)="run(waiting)">
                {{ 'translate.rest' | builderText: text() }}
              </button>
            }
          </section>
        }

        @if (declined(); as reason) {
          <!-- The model's words, quoted: text, never markup, whatever it wrote. -->
          <blockquote data-formancy-part="translate-declined">{{ reason }}</blockquote>
        }

        @if (failure(); as failed) {
          <div data-formancy-part="translate-problems">
            <!-- What the model was told, as it was told it (0119). -->
            <ul>
              @for (problem of failed.problems; track $index) {
                <li>{{ problem.detail }}</li>
              }
            </ul>
            @if (failed.lastAnswer !== '') {
              <details>
                <summary>{{ 'prompt.lastAnswer' | builderText: text() }}</summary>
                <pre>{{ failed.lastAnswer }}</pre>
              </details>
            }
          </div>
        }
      </div>
    }
  `,
})
export class FormancyTranslationReview {
  readonly session = input.required<BuilderSession>()
  /** How to reach a model: the host's, or a relay a person carries (0160). */
  readonly ask = input.required<AskModel>()
  /** The language to fill in. The pane draws this only for one that is not the default. */
  readonly locale = input.required<string>()
  /** How many times to let the model correct itself. Three by default. */
  readonly attempts = input<number | undefined>(undefined)

  protected readonly form = FormancyForm
  protected readonly flags = FLAGS
  protected readonly view = injectBuilderView(this.session)
  /** Every word this part shows, in the language the session was opened in (0114). */
  protected readonly text = computed(() => this.session().text)
  private readonly parent = inject(EnvironmentInjector)

  protected readonly busy = signal(false)
  protected readonly result = signal<TranslationResult | undefined>(undefined)
  protected readonly proposal = signal<TranslationProposal | undefined>(undefined)
  /** What applying said, when it refused. Cleared by anything that moves on. */
  protected readonly refusal = signal<string | undefined>(undefined)

  private static sequence = 0
  private readonly serial = (FormancyTranslationReview.sequence += 1)
  protected readonly reviewId = `formancy-translation-review-${String(this.serial)}`

  /** The stop for the run in flight. A field: pressing it changes nothing on screen by itself. */
  private running: Stop | undefined

  constructor() {
    // Destroyed — another language chosen, another tab — the run stops, and whatever the
    // model answers afterwards is not proposed (0157).
    inject(DestroyRef).onDestroy(() => this.running?.stop())
  }

  protected readonly defaultLocale = computed(() => this.view().document.i18n?.defaultLocale ?? 'en')
  protected readonly missing = computed(
    () => missingMessages(this.view().document, this.locale()).length,
  )
  /** Drawn while there is something to ask for, or a run, an answer or a proposal to show. */
  protected readonly shown = computed(
    () =>
      this.missing() > 0 ||
      this.busy() ||
      this.result() !== undefined ||
      this.proposal() !== undefined,
  )
  /** The proposal under review: none when it writes nothing, and Ask is offered again. */
  protected readonly reviewed = computed(() => translationToReview(this.proposal()))
  /** What the model wrote that was not written, when there is any. */
  protected readonly dropped = computed(() => {
    const dropped = this.proposal()?.dropped ?? []
    return dropped.length === 0 ? undefined : dropped
  })
  protected readonly heading = computed(() => {
    const waiting = this.reviewed()
    return waiting === undefined ? '' : translationHeading(waiting, this.text())
  })
  protected readonly status = computed(() =>
    translationStatus(
      {
        busy: this.busy(),
        result: this.result(),
        proposal: this.proposal(),
        refusal: this.refusal(),
      },
      this.text(),
    ),
  )
  /** The model's reason, when it declined: shown in place of the problems. */
  protected readonly declined = computed(() => {
    const outcome = this.result()
    return outcome === undefined || outcome.ok || outcome.ended !== 'declined'
      ? undefined
      : outcome.reason
  })
  /** A run that ended with answers that did not work. */
  protected readonly failure = computed(() => {
    const outcome = this.result()
    return outcome === undefined ||
      outcome.ok ||
      outcome.ended === 'declined' ||
      outcome.problems.length === 0
      ? undefined
      : outcome
  })

  /** An engine for the form as the proposal would leave it, under ids of its own. */
  protected readonly previewInjector = computed((): Injector | undefined => {
    const waiting = this.reviewed()
    if (waiting === undefined) return undefined
    const document = waiting.document as FormSchema
    return previewInjector(document, this.locale(), this.parent, `${document.id}.proposed`)
  })
  protected readonly previewInputs = computed(() => ({
    submitLabel: this.text()('translations.previewSubmit'),
  }))

  /** Ask for what is missing — over `after`'s document, for the rest of an answer under review. */
  protected async run(after?: TranslationProposal): Promise<void> {
    if (this.busy()) return
    this.busy.set(true)
    this.result.set(undefined)
    this.refusal.set(undefined)
    if (after === undefined) this.proposal.set(undefined)
    const stop = createStop()
    this.running = stop
    try {
      const session = this.session()
      const attempts = this.attempts()
      const outcome = await translateCatalogue(
        this.ask(),
        after?.document ?? session.document(),
        this.locale(),
        { stop, ...(attempts === undefined ? {} : { attempts }) },
      )
      this.result.set(outcome)
      // Held against the form as it is now. Applying later checks it has not moved.
      if (outcome.ok) this.proposal.set(proposeTranslation(session, outcome.answer, after))
    } finally {
      this.running = undefined
      this.busy.set(false)
    }
  }

  protected stop(): void {
    this.running?.stop()
  }

  protected apply(): void {
    const waiting = this.reviewed()
    if (waiting === undefined) return
    const outcome = applyProposal(this.session(), waiting)
    // Kept on screen when refused: the commonest refusal is a form that moved, and the
    // proposal is what the person needs to decide whether to ask again.
    if (outcome.ok) this.discard()
    else this.refusal.set(outcome.message)
  }

  protected discard(): void {
    this.proposal.set(undefined)
    this.refusal.set(undefined)
    this.result.set(undefined)
  }
}

// packages/builder-react/src/translation-review.tsx
import { useEffect, useId, useRef, useState } from 'react'
import type { ReactElement } from 'react'
import {
  applyProposal,
  createStop,
  missingMessages,
  proposeTranslation,
  translateCatalogue,
  translationHeading,
  translationStatus,
  translationToReview,
} from '@formancy/builder-core'
import type {
  AskModel,
  BuilderMessageId,
  BuilderSession,
  Stop,
  TranslationFlag,
  TranslationProposal,
  TranslationResult,
} from '@formancy/builder-core'
import { TranslationsPreview } from './translations-preview.js'
import { useBuilder } from './use-builder.js'

/**
 * Asking a model for the messages a language is missing, and reviewing its answer message
 * by message before it lands.
 *
 * A model's translation is a model's edit, and an edit that changes what a question asks
 * in a language the person reviewing may read less well than the source
 * ([0161](../../../docs/decisions/0161-a-model-translates-only-what-is-missing.md)). So it
 * is shown rather than applied, as the prompt pane's answer is (0109): every message it
 * would write, its source beside what was there and what is proposed, a mark on anything
 * to look at, and the form as it would read in that language. Apply is `applyProposal`,
 * refused when the form has moved since, one undo step otherwise.
 *
 * What is asked, what is kept, what is marked, what is held for review and what the status
 * says are `@formancy/builder-core`'s — `translateCatalogue`, `proposeTranslation`,
 * `translationToReview`, `translationHeading`, `translationStatus` — so the Angular part
 * cannot decide any of them differently (0091). This is the markup, the run's state and its
 * stop.
 *
 * Its own file so the translations pane does not become the place things go: the pane is
 * a translator's table, and this is a model's turn and its review.
 */
export interface TranslationReviewProps {
  session: BuilderSession
  /** How to reach a model: the host's, or a relay a person carries (0160). */
  ask: AskModel
  /** The language to fill in. The pane draws this only for one that is not the default. */
  locale: string
  /** How many times to let the model correct itself. Three by default. */
  attempts?: number | undefined
}

/** What each mark says, in the catalogue's words. */
const FLAGS: Readonly<Record<TranslationFlag, BuilderMessageId>> = {
  stale: 'translate.flag.stale',
  unchanged: 'translate.flag.unchanged',
}

export function TranslationReview({
  session,
  ask,
  locale,
  attempts,
}: TranslationReviewProps): ReactElement | null {
  const view = useBuilder(session)
  const { text } = session
  const [busy, setBusy] = useState(false)
  const [result, setResult] = useState<TranslationResult | undefined>(undefined)
  const [proposal, setProposal] = useState<TranslationProposal | undefined>(undefined)
  /** What applying said, when it refused. Cleared by anything that moves on. */
  const [refusal, setRefusal] = useState<string | undefined>(undefined)
  const reviewId = useId()
  /** The stop for the run in flight. A ref: pressing it changes nothing on screen by itself. */
  const running = useRef<Stop | undefined>(undefined)
  // Taken off the screen — another language chosen, another tab — the run stops, and
  // whatever the model answers afterwards is not proposed (0157).
  useEffect(() => () => running.current?.stop(), [])

  const missing = missingMessages(view.document, locale).length
  if (missing === 0 && !busy && result === undefined && proposal === undefined) return null

  /** The proposal under review: none when it writes nothing, and Ask is offered again. */
  const reviewed = translationToReview(proposal)
  const failed = result?.ok === false ? result : undefined
  const declined = failed?.ended === 'declined' ? failed.reason : undefined
  const problems =
    failed !== undefined && failed.ended !== 'declined' && failed.problems.length > 0
      ? failed
      : undefined

  /** Ask for what is missing — over `after`'s document, for the rest of an answer under review. */
  const run = async (after?: TranslationProposal): Promise<void> => {
    if (busy) return
    setBusy(true)
    setResult(undefined)
    setRefusal(undefined)
    if (after === undefined) setProposal(undefined)
    const stop = createStop()
    running.current = stop
    try {
      const outcome = await translateCatalogue(ask, after?.document ?? session.document(), locale, {
        stop,
        ...(attempts === undefined ? {} : { attempts }),
      })
      setResult(outcome)
      // Held against the form as it is now. Applying later checks it has not moved.
      if (outcome.ok) setProposal(proposeTranslation(session, outcome.answer, after))
    } finally {
      running.current = undefined
      setBusy(false)
    }
  }

  const discard = (): void => {
    setProposal(undefined)
    setRefusal(undefined)
    setResult(undefined)
  }

  const apply = (): void => {
    if (reviewed === undefined) return
    const outcome = applyProposal(session, reviewed)
    // Kept on screen when refused: the commonest refusal is a form that moved, and the
    // proposal is what the person needs to decide whether to ask again.
    if (outcome.ok) discard()
    else setRefusal(outcome.message)
  }

  const defaultLocale = view.document.i18n?.defaultLocale ?? 'en'

  return (
    <div data-formancy-part="translate">
      {reviewed === undefined ? (
        <button
          type="button"
          data-formancy-part="translate-ask"
          disabled={busy}
          onClick={() => void run()}
        >
          {busy ? text('translate.asking') : text('translate.ask', { count: missing })}
        </button>
      ) : null}
      {busy ? (
        <button type="button" onClick={() => running.current?.stop()}>
          {text('prompt.stop')}
        </button>
      ) : null}

      <p role="status" data-formancy-part="translate-status">
        {translationStatus({ busy, result, proposal, refusal }, text)}
      </p>

      {/* Outside the review: when everything the model wrote was dropped there is no review,
          and this is what says why. */}
      {proposal === undefined || proposal.dropped.length === 0 ? null : (
        <p data-formancy-part="translate-dropped">
          {text('translate.dropped', { list: text.list(proposal.dropped) })}
        </p>
      )}

      {reviewed === undefined ? null : (
        <section data-formancy-part="translate-review" aria-labelledby={reviewId}>
          <h3 id={reviewId}>{translationHeading(reviewed, text)}</h3>
          <table data-formancy-part="translate-rows">
            <thead>
              <tr>
                <th scope="col">{defaultLocale}</th>
                <th scope="col">{text('translate.was')}</th>
                <th scope="col">{text('translate.now')}</th>
                <th scope="col">{text('translate.flags')}</th>
              </tr>
            </thead>
            <tbody>
              {reviewed.rows.map((row) => (
                <tr key={row.id}>
                  {/* The source, not the id, as the translations table shows it. */}
                  <th scope="row">{row.source}</th>
                  <td>{row.was === '' ? text('translations.missing') : row.was}</td>
                  {/* The model's words, as text, in the language they are written in. */}
                  <td lang={locale}>{row.now}</td>
                  <td>
                    {row.flags.map((flag) => (
                      <span key={flag} data-formancy-part="translate-flag">
                        {text(FLAGS[flag])}
                      </span>
                    ))}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          {/* The form as it would read in this language, with its own ids beside the pane's
              preview of the form as it is. */}
          <TranslationsPreview
            document={reviewed.document}
            locale={locale}
            label={text('translate.preview', { locale })}
            submitLabel={text('translations.previewSubmit')}
            formId={`${reviewed.document.id}.proposed`}
          />
          <button type="button" disabled={busy} onClick={apply}>
            {text('translate.apply')}
          </button>
          <button type="button" disabled={busy} onClick={discard}>
            {text('prompt.discard')}
          </button>
          {reviewed.stillMissing.length === 0 ? null : (
            <button type="button" disabled={busy} onClick={() => void run(reviewed)}>
              {text('translate.rest')}
            </button>
          )}
        </section>
      )}

      {declined === undefined ? null : (
        /* The model's words, quoted: text, never markup, whatever it wrote. */
        <blockquote data-formancy-part="translate-declined">{declined}</blockquote>
      )}

      {problems === undefined ? null : (
        <div data-formancy-part="translate-problems">
          {/* What the model was told, as it was told it (0119). */}
          <ul>
            {problems.problems.map((problem, index) => (
              <li key={index}>{problem.detail}</li>
            ))}
          </ul>
          {problems.lastAnswer === '' ? null : (
            <details>
              <summary>{text('prompt.lastAnswer')}</summary>
              <pre>{problems.lastAnswer}</pre>
            </details>
          )}
        </div>
      )}
    </div>
  )
}
